'use strict';
/**
 * LONG-TERM (LT) — the RTL Encompass RECONCILIATION field map, brought in for reference.
 *
 * This is a by-VALUE copy of the reconciliation registry from RTL's
 * src/lib/integrations/encompass-field-map.js (owner-authorized 2026-08-14 — see
 * docs/LONG-TERM-AUTHORIZED-COPIES.md). It is the exact set of Encompass fields RTL
 * actively maps/compares between PILOT and Encompass — i.e. the 'mapping' shown in
 * the Encompass Field Registry artifact.
 *
 * WHY IT IS LABELED. These entries describe RTL USAGE: each 'our' points at an RTL
 * column, and the gate/direction/authoritative flags are how RTL's reconciliation
 * treats the field. Long-Term does NOT reconcile anything yet and enforces nothing.
 * This is kept so a developer or AI has the COMPLETE picture of how each Encompass
 * field is used today — the owner's 'certain fields need to be put on the side
 * because they're RTL, but build it up to have a clear picture'. When Long-Term
 * builds its own mapping, it decides field-by-field what to reuse.
 *
 * DATA ONLY. This module carries the DATA (registry, identity map, value maps,
 * gate constants, the purchase-advice date field id). It does NOT copy RTL's
 * reconciliation FUNCTIONS (coerce/compare/flatten) — those are RTL logic tied to
 * RTL's applications table.
 *
 * Field-entry shape: { key, encompassFieldId, loanPath, type, category, compare,
 *   our (the RTL column/target), gate (block|advisory|reference), direction,
 *   authoritative, note, ... }.
 */

// The reconciliation gate levels RTL uses (kept for reference; LT enforces nothing).
const GATE = {
  "BLOCK": "block",
  "ADVISORY": "advisory",
  "REFERENCE": "reference"
};

// The purchase-advice date Encompass field id (env-overridable in RTL).
const PA_DATE_FIELD_ID = "2370";

// The reconciliation registry — every Encompass field RTL maps, by value.
const REGISTRY = [
  {
    "gate": "block",
    "verified": true,
    "key": "ys_loan_number",
    "encompassFieldId": "364",
    "loanPath": "loanNumber",
    "type": "text",
    "category": "program",
    "compare": "text",
    "our": "column:ys_loan_number",
    "note": "Loan number — the natural key; MATCHED (must equal Encompass Loan.LoanNumber, field 364)",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "property_type",
    "encompassFieldId": "1041",
    "loanPath": "property.propertyType",
    "altFieldId": "CX.PROPERTYTYPE",
    "type": "enum",
    "compare": "enum",
    "valueMap": "propertyType",
    "our": "column:property_type",
    "note": "Subject property type (std 1041; CX.PROPERTYTYPE is the tenant cross-check). Our range-category (SFR / Multi 2-4 / Multi 5+ / Condo / Townhouse / Mixed Use) vs Encompass wording is lossy — value-mapped",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": false,
    "key": "units",
    "encompassFieldId": "16",
    "loanPath": [
      "property.financedNumberOfUnits",
      "property.numberOfUnits",
      "property.financedUnits"
    ],
    "type": "int",
    "category": "program",
    "compare": "int",
    "our": "column:units",
    "note": "Number of units — EXACT match (owner-directed 2026-07-26). Encompass standard field 16 (\"No. of Units\"). loanPath candidates need live confirmation against the tenant loan JSON; if it reads blank the field shows \"no data to compare\" (staff must enter it in Encompass)",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "deal_type",
    "encompassFieldId": "CX.DEALPROJECTTYPE",
    "type": "enum",
    "compare": "enum",
    "valueMap": "dealType",
    "our": "derive from applications.program + loan_type (no deal_type column)",
    "note": "Deal/project type — value-mapped (§6). Advisory: our side is derived heuristically from program/loan_type, so a disagreement surfaces but never hard-blocks",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "exit_plan",
    "encompassFieldId": "CX.EXITPLAN",
    "type": "enum",
    "compare": "enum",
    "valueMap": "exitPlan",
    "naWhenOursMissing": true,
    "our": "derived from program/loan_type (flip→sell, hold/rental→hold)",
    "note": "Exit plan — matched: fix & flip → Sale; fix & hold / DSCR rental → Rental/Refinance",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "capital_provider",
    "encompassFieldId": "CX.CAPITALPROVIDER",
    "type": "enum",
    "category": "program",
    "compare": "enum",
    "valueMap": "capitalProvider",
    "nameFallback": true,
    "our": "column:lender (note buyer)",
    "note": "Note buyer / capital provider — STAFF-ONLY. Encompass dropdown read live 2026-07-26: Fidelis Investors / RCN / Roc Capital / Temple View Capital / CorrFirst / BlueLake / EMCAP / Other. nameFallback: an unmapped buyer still compares by name (corporate-form + spelling tolerant) when both sides carry one",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "reference",
    "verified": false,
    "key": "funding_channel",
    "encompassFieldId": "CX.TABLEFUNDER",
    "type": "text",
    "category": "program",
    "compare": "reference",
    "valueMap": "fundingChannel",
    "our": "derive(closing_workflow.warehouse → table_funded)",
    "note": "Funding channel — Table Funding (sold at the closing table) vs direct RTL delegated / with TPR (sold later, so a purchase advice date is expected). Shown for context; the two questions that matter are asked as their own rows (funding_channel_rule / funding_channel_agreement) so an unverified tenant value can never block a term sheet or a tape. valueMap is still declared because funding-channel.js reads it — ONE table for both",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "loan_to_be_vested",
    "encompassFieldId": "CX.LOANTOBEVESTED",
    "type": "enum",
    "compare": "enum",
    "valueMap": "vesting",
    "our": "derive(applications.llc_id present → entity)",
    "note": "Entity vs individual vesting flag",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "vesting_title_role",
    "encompassFieldId": "4008",
    "type": "enum",
    "category": "identity",
    "compare": "enum",
    "valueMap": "vestingTitleRole",
    "naWhenOursMissing": true,
    "our": "derive(applications.llc_id present → Officer; else Individual)",
    "note": "Title vesting role — field 4008. Officer when vested on an LLC; Individual when vested in the borrower's own name. When Individual there is no subject LLC name, so field 1859 becomes not-applicable (see vesting_llc naWhenOursMissing).",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "vesting_llc",
    "encompassFieldId": "1859",
    "loanPath": [
      "closingDocument.finalVestingDescription",
      "vesting.entityName",
      "vesting.trustName",
      "vestingEntityName",
      "uldd.fannieTrustName",
      "closingDocument.borrowerUnparsedName1"
    ],
    "type": "text",
    "category": "identity",
    "compare": "entity",
    "naWhenOursMissing": true,
    "our": "llcs.name via applications.llc_id",
    "note": "Subject LLC / vesting NAME — field 1859. naWhenOursMissing (owner-directed 2026-08-05): when the file has NO subject LLC (vested on an individual), our side is blank, so 1859 reads \"Doesn't apply\" instead of holding the term sheet — the vesting Officer/Individual disagreement, if any, surfaces on field 4008 (vesting_title_role) instead. AUTHORITATIVE source is the fieldReader (read by number). The loanPath list is a best-effort FALLBACK for when the fieldReader is unavailable, and the SAME field lives at a DIFFERENT path from loan to loan: finalVestingDescription reads like \"LAYBACK LLC, A LIMITED LIABILITY COMPANY\" on one loan; VERIFIED LIVE 2026-07-26 on loan YSCAP258134629 (117 Brook) the vesting name lives at closingDocument.borrowerUnparsedName1 / uldd.fannieTrustName (\"MW TRADING LLC\") — finalVestingDescription is absent there. compare:entity strips any trailing legal description so all forms equal our \"MW Trading LLC\". On an INDIVIDUAL-vested loan borrowerUnparsedName1 is a person name; that only matters when the fieldReader is down AND our side carries an llc — a rare degraded case that (correctly) surfaces a disagreement rather than a false match",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "loan_amount",
    "encompassFieldId": "1109",
    "loanPath": "baseLoanAmount",
    "type": "money",
    "category": "loan",
    "compare": "money",
    "wholeDollar": true,
    "our": "column:loan_amount",
    "note": "Total loan amount (Borrower Requested Loan Amount)",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "max_total_loan",
    "encompassFieldId": "CX.MAXTOTALLOAN",
    "type": "money",
    "category": "sizing",
    "compare": "money",
    "wholeDollar": true,
    "our": "column:loan_amount (Encompass second copy of the total)",
    "note": "Max/total loan — must equal our total loan amount",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "final_initial_loan",
    "encompassFieldId": "CX.FINALINITIALLOAN",
    "type": "money",
    "category": "sizing",
    "compare": "money",
    "wholeDollar": true,
    "our": "quote:initialAdvance = loan_amount − financed_rehab − financed_reserve",
    "note": "Final initial advance — compute-only on our side",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "rehab_budget",
    "encompassFieldId": "CX.REHABBUDGET",
    "type": "money",
    "category": "rehab",
    "compare": "money",
    "our": "column:rehab_budget (+ SOW total)",
    "note": "Rehab / construction budget",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "financed_rehab_budget",
    "encompassFieldId": "CX.FINANCEDREHABBUDGET",
    "type": "money",
    "category": "rehab",
    "compare": "money",
    "wholeDollar": true,
    "our": "derive(financed rehab = quote:rehabHoldback; equals rehab_budget unless the OOP-rehab exception was approved)",
    "note": "Financed portion of rehab",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "oop_rehab",
    "encompassFieldId": "CX.OUTOFPOCKETREHAB",
    "type": "money",
    "category": "rehab",
    "compare": "money",
    "zeroMeansNone": true,
    "our": "derive(rehab_budget − quote:rehabHoldback)",
    "note": "Out-of-pocket rehab (borrower-funded; 0 unless the OOP-rehab exception was approved)",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "purchase_price",
    "encompassFieldId": "136",
    "loanPath": "purchasePriceAmount",
    "type": "money",
    "category": "loan",
    "compare": "money",
    "our": "column:purchase_price",
    "note": "Real final purchase price (build-spec §5). NOTE: the discovery doc read 136/purchasePriceAmount as the EFFECTIVE price on assignment deals — confirm which the tenant populates before relying on this on an assignment file",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "effective_purchase",
    "encompassFieldId": "CX.EFFECTIVEPURCHASE",
    "type": "money",
    "category": "cost",
    "compare": "money",
    "wholeDollar": true,
    "our": "quote:assignment.recognizedPrice (seller price + financeable fee)",
    "note": "Effective purchase (LTC basis) — compute-only",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "contract_price",
    "encompassFieldId": "CX.ORIGINALCONTRACTPURCHASEP",
    "type": "money",
    "category": "cost",
    "compare": "money",
    "our": "column:underlying_contract_price (falls back to purchase_price when no assignment)",
    "note": "Seller / underlying contract price (assignment basis)",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "assignment_fee",
    "encompassFieldId": "CX.ASSIGNMENTFEE",
    "type": "money",
    "category": "cost",
    "compare": "money",
    "zeroMeansNone": true,
    "our": "column:assignment_fee",
    "note": "Assignment fee (financeable per frozen engine: lesser of 15% of contract / $75k)",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "financed_interest_reserve",
    "encompassFieldId": "CX.FINANCEDINTERESTRESERVE",
    "type": "money",
    "category": "cost",
    "compare": "money",
    "zeroMeansNone": true,
    "wholeDollar": true,
    "our": "quote:financedReserve$ (from requested_ir_months / requested_ir_amount)",
    "note": "Financed interest reserve $ — compute-only; can be 0",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "total_cost",
    "encompassFieldId": "CX.TOTALCOST",
    "type": "money",
    "category": "cost",
    "compare": "money",
    "wholeDollar": true,
    "our": "derive(min(effective purchase, as-is) + rehab + financed reserve + program extras)",
    "note": "Total cost (LTC basis) — no column, derive",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "as_is_value",
    "encompassFieldId": "CX.ASISVALUE",
    "type": "money",
    "category": "valuation",
    "compare": "money",
    "our": "column:as_is_value",
    "note": "As-is value (NOT std 356 — 356 is ARV$ on this tenant)",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "arv",
    "encompassFieldId": "356",
    "loanPath": "propertyAppraisedValueAmount",
    "type": "money",
    "category": "valuation",
    "compare": "money",
    "our": "column:arv",
    "note": "ARV in dollars (propertyAppraisedValueAmount)",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "actual_arv_ltv",
    "encompassFieldId": "CX.ACTAULARV",
    "type": "percent",
    "category": "valuation",
    "compare": "percent",
    "our": "quote:actual ARV-LTV",
    "note": "Actual ARV-LTV % (final loan ÷ ARV) — compute-only",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "actual_ltc",
    "encompassFieldId": "CX.ACTAULLTC",
    "type": "percent",
    "category": "sizing",
    "compare": "percent",
    "our": "quote:actual LTC",
    "note": "Actual LTC % — compute-only",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "actual_initial_ltv",
    "encompassFieldId": "CX.ACTUALINITIALLTV",
    "type": "percent",
    "category": "sizing",
    "compare": "percent",
    "our": "column:ltv (stores actual acq/initial LTV)",
    "note": "Actual initial LTV % — advisory, like the other actual/cap percents",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "max_initial_ltv",
    "encompassFieldId": "CX.MAXINITIALLTV",
    "type": "percent",
    "category": "sizing",
    "compare": "percent",
    "our": "quote:guidelines.caps.initialLtv",
    "note": "Program MAX initial LTV — compute-only",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "max_arv_ltv",
    "encompassFieldId": "CX.MAXARV",
    "type": "percent",
    "category": "valuation",
    "compare": "percent",
    "our": "quote:guidelines.caps.arvLtv",
    "note": "Program MAX ARV-LTV — compute-only",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "max_ltc",
    "encompassFieldId": "CX.MAXLTC",
    "type": "percent",
    "category": "sizing",
    "compare": "percent",
    "our": "quote:guidelines.caps.ltc",
    "note": "Program MAX LTC — compute-only",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "note_rate",
    "encompassFieldId": "3",
    "loanPath": "requestedInterestRatePercent",
    "type": "rate",
    "category": "interest",
    "compare": "percent",
    "our": "column:rate_pct",
    "note": "Interest rate — PERCENT on both sides. WO-B MUST source applications.rate_pct (a percent, e.g. 10.99), NOT the fractional whole-loan-context note_rate (0.1099), or every loan false-mismatches",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "origination_pct",
    "encompassFieldId": "388",
    "loanPath": [
      "originationFeePercent",
      "closingCost.originationFeePercentage"
    ],
    "type": "percent",
    "category": "cost",
    "compare": "percent",
    "our": "quote:origination % (e.g. 1.25)",
    "note": "Origination fee % — field 388. Read authoritatively BY FIELD NUMBER (fieldReader → 1.000 = 1%), the same scale as our origPct*100. The GFE loanOriginationPercentage path is deliberately NOT a fallback — it is a different fee (points/adjusted origination) and reads 2 where field 388 is 1",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "term_months",
    "encompassFieldId": "4",
    "loanPath": "loanAmortizationTermMonths",
    "type": "int",
    "category": "loan",
    "compare": "int",
    "our": "column:term (text → int)",
    "note": "Term in months",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "block",
    "verified": true,
    "key": "maturity_date",
    "encompassFieldId": "78",
    "loanPath": "maturityDate",
    "type": "date",
    "category": "loan",
    "compare": "date",
    "our": "column:maturity_date",
    "note": "Maturity date — read from full loan (maturityDate), not pipeline",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "reference",
    "verified": true,
    "key": "funded_date",
    "encompassFieldId": "CX.FUNDEDDATE",
    "skipBatch": true,
    "loanPath": "closingDocument.fundingDate",
    "type": "date",
    "category": "loan",
    "compare": "reference",
    "our": "column:funded_date",
    "note": "Funded date — read from the custom field CX.FUNDEDDATE (the tenant's real funded date), with closingDocument.fundingDate as a JSON fallback. NEVER field 1401 (that is Encompass \"Loan Program\" — it returns the program name, which is what wrongly showed in this row). skipBatch keeps CX.FUNDEDDATE OUT of the by-number fieldReader batch (allFieldIds) so an unreadable custom id can never blank the whole read (the #1131 regression); it is read via customFields[] passthrough + the loanPath instead. Read-only reference; shown for info, never gates the term sheet (empty until funding); the closing reconciliation gate reads the value separately.",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "reference",
    "verified": false,
    "key": "purchase_advice_date",
    "encompassFieldId": "2370",
    "type": "date",
    "category": "loan",
    "compare": "reference",
    "our": "column:purchase_advice_date",
    "note": "Purchase advice date — field 2370, supplied by the owner 2026-08-09. Read-only reference: present = the loan was sold to the investor. Blank does NOT mean \"not sold\" on its own — a TABLE FUNDED loan was sold at the closing table and never receives one (see src/lib/funding-channel.js), which is why release-party.soldStatus checks table funding FIRST. Drives a warning at investor delivery and the 30-day chase; gates nothing. ENCOMPASS_PA_DATE_FIELD_ID overrides the id, and setting it blank switches the field off entirely",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "total_experience_deals",
    "encompassFieldId": "CX.TOTALEXPERIENCEDEALS",
    "type": "int",
    "category": "experience",
    "compare": "int",
    "zeroMeansNone": true,
    "our": "derive(requested_exp_flips/holds/ground + verified track record)",
    "note": "Verified experience count used to qualify — 0 and blank mean the same thing (a first-time borrower)",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "rehab_type",
    "encompassFieldId": "CX.REHABTYPE",
    "type": "enum",
    "category": "rehab",
    "compare": "enum",
    "valueMap": "rehabType",
    "our": "column:rehab_type",
    "note": "Rehab type — value-mapped (§6): Light/Cosmetic → light, Heavy → heavy, Expansion → adding SF. Advisory: our 5 buckets (incl. Moderate) have no Encompass counterpart, so a bucket difference surfaces but never blocks",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "advisory",
    "verified": true,
    "key": "accrual_type",
    "encompassFieldId": "CX.ACCRUALTYPE",
    "type": "enum",
    "category": "interest",
    "compare": "enum",
    "valueMap": "accrual",
    "our": "column:accrual_type",
    "note": "Accrual basis — advisory; Drawn/Non-Dutch → non_dutch, Note/Dutch → dutch",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "reference",
    "verified": true,
    "key": "ref_cash_to_close",
    "encompassFieldId": "CX.RTLCASHTOCLOSEESTIMAT",
    "type": "money",
    "category": "cost",
    "compare": "reference",
    "our": "none",
    "note": "Estimated cash to close — reference only",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "reference",
    "verified": true,
    "key": "ref_down_payment",
    "encompassFieldId": "CX.RTLDOWNPAYMENT",
    "type": "money",
    "category": "cost",
    "compare": "reference",
    "our": "none",
    "note": "Down payment — reference only",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "reference",
    "verified": true,
    "key": "ref_cross_collateralized",
    "encompassFieldId": "CX.CROSSCOLLATERALIZEDFLAG",
    "type": "text",
    "category": "program",
    "compare": "reference",
    "our": "none",
    "note": "Cross-collateralized flag — reference only",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  },
  {
    "gate": "reference",
    "verified": true,
    "key": "ref_multi_property",
    "encompassFieldId": "CX.MULTIPROPERTYFLAG",
    "type": "text",
    "category": "program",
    "compare": "reference",
    "our": "none",
    "note": "Multi-property flag — reference only",
    "direction": "pull",
    "authoritative": "pilot",
    "blocksCtc": false,
    "blocksFunding": false
  }
];

// Identity fields (borrower/co-borrower name, DOB, SSN, phones, email, vesting).
const IDENTITY_MAP = [
  {
    "key": "first_name",
    "our": "borrowers.first_name",
    "enc": "applications[].{party}.firstName",
    "stdFieldId": {
      "borrower": "4000",
      "coBorrower": "4004"
    },
    "match": "nameEquals"
  },
  {
    "key": "last_name",
    "our": "borrowers.last_name",
    "enc": "applications[].{party}.lastName",
    "stdFieldId": {
      "borrower": "4002",
      "coBorrower": "4006"
    },
    "match": "nameEquals"
  },
  {
    "key": "middle_name",
    "our": "borrowers.middle_name",
    "enc": "applications[].{party}.middleName",
    "stdFieldId": {
      "borrower": "4001",
      "coBorrower": "4005"
    },
    "match": "nameEqualsLoose",
    "note": "Middle name — optional on our side; a blank on either side is not a disagreement"
  },
  {
    "key": "name_suffix",
    "our": "borrowers.name_suffix",
    "enc": "applications[].{party}.suffixToName",
    "match": "nameEqualsLoose",
    "note": "Generational/professional suffix (Jr., III). Kept OUT of last_name so the surname compares cleanly"
  },
  {
    "key": "date_of_birth",
    "our": "borrowers.date_of_birth",
    "enc": "applications[].{party}.birthDate",
    "stdFieldId": {
      "borrower": "1402",
      "coBorrower": "1403"
    },
    "match": "dateEquals",
    "sensitive": true,
    "note": "Respect sanitizeDob + DOB-review rules"
  },
  {
    "key": "ssn",
    "our": "borrowers.ssn_hash / ssn_last4",
    "enc": "applications[].{party}.taxIdentificationIdentifier",
    "stdFieldId": {
      "borrower": "65",
      "coBorrower": "97"
    },
    "match": "ssnHash",
    "sensitive": true,
    "note": "Compare by HMAC hash / last-4 ONLY; reveal stays behind the audited view_ssn gate; never fetch-print-store plaintext"
  },
  {
    "key": "current_address",
    "our": "borrowers.current_address (jsonb)",
    "enc": "applications[].{party}.residences[] (current) / mailing",
    "match": "addressCanon",
    "note": "Canonicalize with address-canon.samePlace"
  },
  {
    "key": "phone",
    "our": "borrowers.cell_phone",
    "enc": "applications[].{party}.homePhoneNumber / mobilePhone / workPhoneNumber",
    "stdFieldId": {
      "borrower": [
        "66",
        "1490",
        "4533"
      ],
      "coBorrower": [
        "98",
        "1480",
        "4534"
      ]
    },
    "match": "digitsEqualsAny",
    "note": "Home / cell / work — our one number matches any of the three"
  },
  {
    "key": "email",
    "our": "borrowers.email",
    "enc": "applications[].{party}.emailAddressText",
    "stdFieldId": {
      "borrower": "1240",
      "coBorrower": "1268"
    },
    "match": "lowerEquals"
  },
  {
    "key": "vesting_llc",
    "our": "llcs.name via applications.llc_id",
    "enc": "field 1859 (subject LLC vesting name)",
    "stdFieldId": {
      "borrower": "1859"
    },
    "match": "nameEquals",
    "note": "Owner-directed: match field 1859 with our subject LLC vesting"
  }
];

// Value maps — how RTL normalizes Encompass enum values for comparison.
const VALUE_MAPS = {
  "dealType": {
    "fix and flip": "flip",
    "fix & flip": "flip",
    "flip": "flip",
    "rehab": "flip",
    "fix and hold": "fix-and-hold",
    "fix & hold": "fix-and-hold",
    "fix-and-hold": "fix-and-hold",
    "brrr": "fix-and-hold",
    "hold": "fix-and-hold",
    "new construction": "ground-up",
    "ground up": "ground-up",
    "ground-up": "ground-up",
    "construction": "ground-up",
    "bridge": "bridge",
    "rental": "rental",
    "dscr": "rental",
    "long-term rental": "rental"
  },
  "exitPlan": {
    "sale": "sell",
    "sell": "sell",
    "sell/sale": "sell",
    "sale/sell": "sell",
    "resale": "sell",
    "fix and flip": "sell",
    "fix & flip": "sell",
    "flip": "sell",
    "sell property": "sell",
    "market sale": "sell",
    "refinance: rental": "hold",
    "refinance: long term": "hold",
    "refinance - rental": "hold",
    "refinance": "hold",
    "refi": "hold",
    "rent": "hold",
    "rental": "hold",
    "hold": "hold",
    "rent/refinance": "hold",
    "refinance/rental": "hold",
    "long term rental": "hold",
    "buy and hold": "hold"
  },
  "capitalProvider": {
    "fidelis": "fidelis",
    "fidelis investors": "fidelis",
    "fidelis investments": "fidelis",
    "fidelis investments llc": "fidelis",
    "fidelis investors llc": "fidelis",
    "blue lake": "bluelake",
    "bluelake": "bluelake",
    "blue lake capital": "bluelake",
    "corrfirst": "corrfirst",
    "corr first": "corrfirst",
    "emcap": "emcap",
    "em cap": "emcap",
    "emcap financial": "emcap",
    "em cap financial": "emcap",
    "emcap financial llc": "emcap",
    "rcn": "rcn",
    "rcn capital": "rcn",
    "roc capital": "roccapital",
    "roc": "roccapital",
    "roc360": "roccapital",
    "temple view capital": "templeview",
    "temple view": "templeview",
    "templeview": "templeview",
    "other": "other"
  },
  "fundingChannel": {
    "0": "direct",
    "1": "table_funding",
    "table funding": "table_funding",
    "table funded": "table_funding",
    "tablefunding": "table_funding",
    "table fund": "table_funding",
    "table-funding": "table_funding",
    "table funder": "table_funding",
    "y": "table_funding",
    "yes": "table_funding",
    "true": "table_funding",
    "n": "direct",
    "no": "direct",
    "false": "direct",
    "direct rtl": "direct",
    "direct": "direct",
    "direct rtl / delegate": "direct",
    "direct rtl/delegate": "direct",
    "direct rtl delegate": "direct",
    "direct rtl - delegate": "direct",
    "direct / delegate": "direct",
    "direct delegate": "direct",
    "delegate": "direct",
    "delegated": "direct",
    "direct rtl / w tpr": "direct",
    "direct rtl/w tpr": "direct",
    "direct rtl w tpr": "direct",
    "direct rtl - w tpr": "direct",
    "direct rtl / with tpr": "direct",
    "direct rtl with tpr": "direct",
    "direct / w tpr": "direct",
    "direct w tpr": "direct",
    "w tpr": "direct",
    "with tpr": "direct",
    "tpr": "direct"
  },
  "rehabType": {
    "cosmetic": "light",
    "cosmetic rehab": "light",
    "light rehab": "light",
    "light": "light",
    "moderate": "light",
    "moderate rehab": "light",
    "medium": "light",
    "cosmetic / light": "light",
    "cosmetic/light": "light",
    "heavy rehab": "heavy",
    "heavy": "heavy",
    "heavy / gut rehab": "heavy",
    "heavy/gut rehab": "heavy",
    "gut rehab": "heavy",
    "gut": "heavy",
    "heavy gut rehab": "heavy",
    "expansion": "expansion",
    "adding sf": "expansion",
    "add sf": "expansion",
    "adding square footage": "expansion",
    "adding square feet": "expansion",
    "sqft addition": "expansion",
    "square footage expansion": "expansion",
    "new construction": "ground-up",
    "ground-up": "ground-up",
    "ground up": "ground-up",
    "ground-up construction": "ground-up",
    "ground up construction": "ground-up",
    "groundup": "ground-up"
  },
  "accrual": {
    "drawn": "non_dutch",
    "as-drawn": "non_dutch",
    "as drawn": "non_dutch",
    "non-dutch": "non_dutch",
    "non dutch": "non_dutch",
    "nondutch": "non_dutch",
    "non_dutch": "non_dutch",
    "note": "dutch",
    "dutch": "dutch",
    "full-boat": "dutch",
    "full boat": "dutch",
    "fullboat": "dutch"
  },
  "vesting": {
    "entity": "entity",
    "llc": "entity",
    "corporation": "entity",
    "corp": "entity",
    "trust": "entity",
    "individual": "individual",
    "person": "individual",
    "natural person": "individual"
  },
  "vestingTitleRole": {
    "officer": "officer",
    "authorized officer": "officer",
    "auth officer": "officer",
    "authorized signer": "officer",
    "managing member": "officer",
    "member": "officer",
    "manager": "officer",
    "entity": "officer",
    "llc": "officer",
    "individual": "individual",
    "individuals": "individual",
    "person": "individual",
    "natural person": "individual",
    "borrower": "individual"
  },
  "propertyType": {
    "sfr": "sfr",
    "single family": "sfr",
    "single family residence": "sfr",
    "singlefamily": "sfr",
    "sfr (1 unit)": "sfr",
    "1 unit": "sfr",
    "detached": "sfr",
    "multi 2-4": "multi_2_4",
    "2-4 family": "multi_2_4",
    "2-4 units": "multi_2_4",
    "2-4 unit": "multi_2_4",
    "two to four family": "multi_2_4",
    "duplex": "multi_2_4",
    "triplex": "multi_2_4",
    "fourplex": "multi_2_4",
    "multi 5+": "multi_5plus",
    "multi 5plus": "multi_5plus",
    "multifamily": "multi_5plus",
    "multi-family": "multi_5plus",
    "5+ units": "multi_5plus",
    "condo": "condo",
    "condominium": "condo",
    "townhouse": "townhouse",
    "townhome": "townhouse",
    "town home": "townhouse",
    "town house": "townhouse",
    "mixed use": "mixed_use",
    "mixed-use": "mixed_use"
  }
};

module.exports = { GATE, PA_DATE_FIELD_ID, REGISTRY, IDENTITY_MAP, VALUE_MAPS };
