'use strict';
/**
 * PAYING AN APPRAISALSCOPE ORDER — the three ways, actually carried out.
 *
 * Owner-directed 2026-08-16: *"I want to be a real vendor charge, yes. I want them
 * to charge the credit card that I'm importing."*
 *
 * Until now AppraisalScope was `back_office` in `lib/appraisal/payment-options.js`:
 * pressing a way wrote down what somebody intended to do by hand, because no
 * payment request had ever been verified against the vendor's contract. The
 * vendor's own client package is now in this repository
 * (`docs/vendor/appraisalscope/`), so the requests are built from their samples
 * field for field and the three ways are real:
 *
 *   CARD_ON_FILE  the card saved on this loan file is charged, now
 *   NEW_CARD      a card typed in is saved onto the file, then charged
 *   PAYMENT_LINK  the vendor emails their own invoice / payment page
 *
 * STILL MANUAL, WHICH IS THE STANDING RULE AND IS NOT WEAKENED HERE. Nothing in
 * this module runs on a timer, a poll, an order creation or any other event. A
 * person opens an order, chooses a way, and presses a button; this is what happens
 * when they do. PILOT never decides to charge somebody.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * THE FIVE RULES THIS FILE IS BUILT AROUND — every one of them is about the fact
 * that a charge cannot be taken back by pressing the button again.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * 1. ONE PRESS, ONE CHARGE — CLAIM BEFORE YOU SEND. `charge_started_at` is taken
 *    with an `IS NULL`-guarded UPDATE before a single byte goes out, so a double
 *    click, a retried request, a second staffer on the same order, or two web
 *    processes can only ever produce one winner. The loser is told the charge is
 *    already running, not sent a second one.
 *
 * 2. THE CLAIM IS RELEASED ONLY WHEN NOTHING REACHED THE VENDOR. A transport
 *    failure — the switch is off, the connection died, the gateway 500'd before
 *    reading the body — means no charge, so the claim is released and the button
 *    works again. Anything the vendor ANSWERED, including an answer we could not
 *    parse, keeps the claim: *"we do not know whether that went through"* is a
 *    question for a human, and never a reason for software to try again.
 *
 * 3. A PAID ORDER IS NEVER CHARGED AGAIN. A recorded `vendor_transaction_id` is a
 *    refusal, full stop. Undoing it is a deliberate, audited human act elsewhere.
 *
 * 4. THE CARD IS DECRYPTED IN MEMORY AND NEVER LOGGED. The number and the security
 *    code exist as strings for the length of one request. They are never returned
 *    to a caller, never journaled (`cdg.maskRequest` blanks the code entirely and
 *    keeps only the last four of the number — and a test asserts it), and never
 *    put in an error message.
 *
 * 5. NOTHING IS GUESSED. Every field name comes from the vendor's own samples. The
 *    fee is NOT sent: their guide says `PaymentAuthCapture` *"authorizes and
 *    charges a credit card for the full payment amount"* already agreed on the
 *    order, so naming a number would be us choosing the price.
 */

const cdg = require('./cdg');
const client = require('./client');
const session = require('./session');
const apprCard = require('../lib/appraisal-card');
const payOptions = require('../lib/appraisal/payment-options');
const C = require('../lib/crypto');

/**
 * OUR OWN HANDLE FOR THIS PAYMENT.
 *
 * `paymentReferenceIdentifier` is generated by the CLIENT — the vendor does not
 * hand one back first — and a later `PaymentCapture` against their PCI vault is
 * addressed to it. It is derived from the order id so it is STABLE: the same order
 * re-presented after an unreadable answer carries the same reference, which gives
 * the vendor every chance to recognise a repeat rather than treating it as a
 * second, unrelated payment. (That is a courtesy, not the safety mechanism — the
 * claim in rule 1 is.)
 */
function referenceFor(orderId) { return `YSAP-${orderId}`; }

/**
 * THE CARD, DECRYPTED, FOR EXACTLY ONE REQUEST.
 *
 * Reads the SAME per-file row and the SAME encrypted blob the rest of the codebase
 * uses — a card is decrypted one way here, and this is that way. Returns null
 * rather than throwing on anything unreadable: the caller turns that into a plain
 * sentence for a person, because "the card on this file cannot be read" is
 * actionable and a stack trace is not.
 */
async function loadCard(dbh, appId) {
  const row = (await dbh.query(
    `SELECT card_encrypted, last4, brand, exp_month, exp_year, billing_zip
       FROM application_payment_cards WHERE application_id=$1`, [appId])).rows[0];
  if (!row || !row.card_encrypted) return null;
  let full = null;
  try { full = JSON.parse(C.decryptSSN(Buffer.from(row.card_encrypted, 'base64'))); } catch (_) { full = null; }
  if (!full || !full.number) return null;
  return {
    number: String(full.number),
    // THE SECURITY CODE IS WHY THIS FEATURE WORKS AT ALL. `PaymentAuthCapture`
    // requires it, and it is stored inside this same encrypted blob at the owner's
    // direction — so the card on file can be charged without going back to the
    // borrower. An older row saved before the code was captured simply has none,
    // and the caller says so rather than sending a request that would be declined.
    cvc: full.cvc ? String(full.cvc) : null,
    last4: row.last4 || null,
    brand: row.brand || null,
    expMonth: row.exp_month,
    expYear: row.exp_year,
    zip: row.billing_zip || null,
  };
}

/** Who the card belongs to and where they are — the cardholder block's non-card half. */
async function loadHolder(dbh, appId) {
  const row = (await dbh.query(
    `SELECT b.first_name, b.last_name, b.email, b.cell_phone, b.current_address,
            a.ys_loan_number
       FROM applications a JOIN borrowers b ON b.id = a.borrower_id
      WHERE a.id=$1 AND a.deleted_at IS NULL`, [appId])).rows[0];
  if (!row) return null;
  const addr = row.current_address && typeof row.current_address === 'object' ? row.current_address : {};
  return {
    firstName: row.first_name || null,
    lastName: row.last_name || null,
    email: row.email || null,
    phone: row.cell_phone || null,
    address1: addr.line1 || addr.street || null,
    address2: addr.line2 || addr.unit || null,
    city: addr.city || null,
    state: addr.state || null,
    postalCode: addr.zip || addr.postalCode || null,
    loanNumber: row.ys_loan_number || null,
  };
}

/** The order, and the vendor references a payment has to be addressed to. */
async function loadOrder(dbh, orderId) {
  return (await dbh.query(
    `SELECT id, application_id, client_order_number, sp_order_number, sp_subdomain, status
       FROM amc_orders WHERE id=$1`, [orderId])).rows[0] || null;
}

/**
 * CLAIM THE RIGHT TO CHARGE THIS ORDER. Rule 1.
 *
 * Also creates the instruction row if there is not one yet, so a staffer who
 * presses "charge the card on file" without having first recorded a choice is not
 * refused for a bookkeeping reason. Returns the claimed row, or null when somebody
 * else holds the claim.
 *
 * The `charge_started_at IS NULL` in the DO UPDATE's WHERE is the whole mechanism:
 * Postgres applies it under the row lock the conflict already took, so two
 * simultaneous callers cannot both see NULL.
 */
async function claimCharge(dbh, { appId, orderId, method, staffId }) {
  const r = await dbh.query(
    `INSERT INTO appraisal_payment_intents
       (application_id, vendor, vendor_order_id, method, chosen_by, performed_by, charge_started_at)
     VALUES ($1::uuid, 'nan', $2::bigint, $3::text, $4::uuid, 'vendor', now())
     ON CONFLICT (vendor, vendor_order_id) DO UPDATE SET
       method            = EXCLUDED.method,
       performed_by      = 'vendor',
       chosen_by         = COALESCE(appraisal_payment_intents.chosen_by, EXCLUDED.chosen_by),
       charge_started_at = now(),
       charge_error      = NULL
     WHERE appraisal_payment_intents.charge_started_at IS NULL
       AND appraisal_payment_intents.vendor_transaction_id IS NULL
     RETURNING *`,
    [appId, orderId, method, staffId || null]);
  return r.rows[0] || null;
}

/** Release the claim — ONLY when nothing reached the vendor. Rule 2. */
async function releaseCharge(dbh, orderId, error) {
  try {
    await dbh.query(
      `UPDATE appraisal_payment_intents
          SET charge_started_at = NULL, charge_error = $2
        WHERE vendor='nan' AND vendor_order_id=$1::bigint AND vendor_transaction_id IS NULL`,
      [orderId, error ? String(error).slice(0, 400) : null]);
  } catch (_) { /* the refusal already reached the caller; this is bookkeeping */ }
}

/** Record the receipt. This is the row that says the money moved. */
async function recordCharge(dbh, orderId, { transactionId, reference, staffId }) {
  const r = await dbh.query(
    `UPDATE appraisal_payment_intents
        SET vendor_transaction_id = $2,
            payment_reference     = COALESCE($3, payment_reference),
            settled_at            = COALESCE(settled_at, now()),
            settled_by            = COALESCE(settled_by, $4::uuid),
            charge_error          = NULL
      WHERE vendor='nan' AND vendor_order_id=$1::bigint
      RETURNING *`,
    [orderId, transactionId, reference || null, staffId || null]);
  return r.rows[0] || null;
}

/**
 * The state a person needs before they press anything: is it already paid, is
 * there a charge in flight, is the card usable, and which ways are open.
 * NEVER throws and NEVER reveals a card number.
 */
async function paymentState(dbh, orderId) {
  const order = await loadOrder(dbh, orderId);
  if (!order) return { ok: false, error: 'no_order' };
  const intent = (await dbh.query(
    `SELECT * FROM appraisal_payment_intents WHERE vendor='nan' AND vendor_order_id=$1::bigint`,
    [orderId])).rows[0] || null;
  const card = await apprCard.cardStatus(dbh, order.application_id);
  // A card saved before the security code was captured cannot be charged — say so
  // HERE, on the screen, rather than letting somebody press a button that the
  // vendor will decline for a reason nobody in this building can see.
  let cardChargeable = card.present && !card.expired;
  let cardReason = null;
  if (card.present) {
    const full = await loadCard(dbh, order.application_id);
    if (!full) { cardChargeable = false; cardReason = 'The card on this file cannot be read — enter it again.'; }
    else if (!full.cvc) {
      cardChargeable = false;
      cardReason = 'The card on this file was saved without its security code, which AppraisalScope requires — enter the card again.';
    }
  }
  return {
    ok: true,
    orderId: order.id,
    applicationId: order.application_id,
    card,
    cardChargeable,
    cardReason,
    paid: !!(intent && intent.vendor_transaction_id),
    charging: !!(intent && intent.charge_started_at && !intent.vendor_transaction_id),
    transactionId: intent ? intent.vendor_transaction_id : null,
    lastError: intent ? intent.charge_error : null,
    intent,
    options: payOptions.optionsFor('nan', { cardOnFile: card }),
  };
}

/**
 * CHARGE THE ORDER. The whole point of the module.
 *
 * @param {object} dbh    a db handle
 * @param {object} opts
 * @param {number} opts.orderId
 * @param {string} opts.method   'CARD_ON_FILE' | 'NEW_CARD'
 * @param {object} [opts.card]   raw card input, required for NEW_CARD
 * @param {string} [opts.staffId]
 * @param {object} [opts.deps]   inject { transport, authContext } in tests
 * @returns {Promise<{ok:boolean, transactionId?:string, error?:string, detail?:string}>}
 *
 * NEVER THROWS. Every outcome is a shaped answer, because the one thing a payment
 * screen must never do is turn an unknown state into a stack trace.
 */
async function charge(dbh, opts = {}) {
  const { orderId, method, staffId = null, deps = {} } = opts;
  const m = String(method || '').toUpperCase();
  if (m !== 'CARD_ON_FILE' && m !== 'NEW_CARD') {
    return { ok: false, error: 'unknown_method', detail: 'A card charge is either the card on file or a card entered now.' };
  }
  const order = await loadOrder(dbh, orderId);
  if (!order) return { ok: false, error: 'no_order' };

  // RULE 3, ASKED FIRST. Refusing early costs one cheap read and is the difference
  // between "already paid" and a second charge on a borrower's card.
  const existing = (await dbh.query(
    `SELECT vendor_transaction_id FROM appraisal_payment_intents
      WHERE vendor='nan' AND vendor_order_id=$1::bigint`, [orderId])).rows[0];
  if (existing && existing.vendor_transaction_id) {
    return {
      ok: false, error: 'already_paid', transactionId: existing.vendor_transaction_id,
      detail: `This order was already paid — AppraisalScope's receipt is ${existing.vendor_transaction_id}.`,
    };
  }

  // A card typed in now is SAVED FIRST, through the shared chokepoint, so it fills
  // the appraisal-payment condition exactly as entering it on the condition would
  // — and so that a charge that then fails still leaves the card where the next
  // attempt can find it.
  let saved = null;
  if (m === 'NEW_CARD') {
    const v = apprCard.validateCardInput(opts.card || {});
    if (!v.ok) return { ok: false, error: 'bad_card', detail: v.error };
    const app = (await dbh.query(
      `SELECT borrower_id FROM applications WHERE id=$1 AND deleted_at IS NULL`, [order.application_id])).rows[0];
    if (!app) return { ok: false, error: 'no_application' };
    saved = await apprCard.saveApplicationCard({
      appId: order.application_id, borrowerId: app.borrower_id,
      number: v.number, cvc: v.cvc, expMonth: v.expMonth, expYear: v.expYear, zip: v.zip,
      // On OUR handle: the save and the charge are one action from the user's side,
      // and a card written to the pool would be invisible to a caller running this
      // inside a transaction — which is exactly how the read two lines later would
      // then fail to find the card that had just been entered.
      dbc: dbh });
  }

  const card = await loadCard(dbh, order.application_id);
  if (!card) {
    return {
      ok: false, error: 'no_card',
      detail: 'There is no readable card on this file — enter one, or send the borrower a payment link.',
    };
  }
  if (!card.cvc) {
    return {
      ok: false, error: 'no_security_code',
      detail: 'The card on this file was saved without its security code, which AppraisalScope requires. Enter the card again.',
    };
  }

  const holder = await loadHolder(dbh, order.application_id);
  if (!holder) return { ok: false, error: 'no_application' };

  // RULE 1. Nothing is sent until this returns a row.
  const claimed = await claimCharge(dbh, { appId: order.application_id, orderId, method: m, staffId });
  if (!claimed) {
    return {
      ok: false, error: 'charge_in_flight',
      detail: 'A payment on this order is already going through. Give it a moment, then reload before trying again.',
    };
  }

  const reference = referenceFor(orderId);
  let answered = false;
  try {
    const transport = deps.transport || client;
    const ctx = deps.authContext || (await session.authContext());
    const req = cdg.buildPaymentAuthCapture({
      apiKey: ctx.apiKey,
      subdomain: order.sp_subdomain || ctx.subdomain,
      clientOrderNumber: order.client_order_number,
      spOrderNumber: order.sp_order_number,
      payment: {
        referenceId: reference,
        firstName: holder.firstName, lastName: holder.lastName,
        address1: holder.address1, address2: holder.address2,
        city: holder.city, state: holder.state, postalCode: holder.postalCode || card.zip,
        phone: holder.phone, email: holder.email,
        cardNumber: card.number, securityCode: card.cvc,
        expMonth: card.expMonth, expYear: card.expYear,
      },
    });
    // From here on the vendor may have taken the money. `answered` is what decides
    // whether the claim is released — see rule 2.
    const resp = await transport.write(req, { label: 'PaymentAuthCapture' });
    answered = true;

    const err = cdg.parseError(resp);
    if (err) {
      // THE VENDOR REFUSED — a decline, a bad card, a closed order. Nothing was
      // taken, so the claim is released and the button works again; their own
      // words are kept so the desk can say why.
      await releaseCharge(dbh, orderId, err.description || err.code || 'refused');
      return { ok: false, error: 'declined', detail: err.description || `AppraisalScope refused the payment (${err.code}).` };
    }

    const txn = cdg.parsePaymentTransactionId(resp);
    if (!txn) {
      // ANSWERED, NOT REFUSED, NO RECEIPT. We genuinely do not know. The claim
      // STAYS so nobody can quietly charge again, and a person is told to check
      // with the vendor — which is the honest state and the safe one.
      await dbh.query(
        `UPDATE appraisal_payment_intents SET charge_error=$2
          WHERE vendor='nan' AND vendor_order_id=$1::bigint`,
        [orderId, 'AppraisalScope answered without a transaction id — check with them before charging again.']);
      return {
        ok: false, error: 'no_receipt',
        detail: 'AppraisalScope answered but did not send back a payment receipt, so we cannot tell whether the card was '
          + 'charged. Check the order on their side before trying again — this one is deliberately left locked.',
      };
    }

    const intent = await recordCharge(dbh, orderId, { transactionId: txn, reference, staffId });
    return { ok: true, transactionId: txn, reference, intent, cardSaved: saved, last4: card.last4, brand: card.brand };
  } catch (e) {
    // NOTHING REACHED THEM (or the reply never arrived). Release, and say what
    // happened in the vendor's own words where we have them.
    const detail = String((e && e.message) || e);
    if (!answered) await releaseCharge(dbh, orderId, detail);
    else {
      try {
        await dbh.query(
          `UPDATE appraisal_payment_intents SET charge_error=$2
            WHERE vendor='nan' AND vendor_order_id=$1::bigint`, [orderId, detail.slice(0, 400)]);
      } catch (_) { /* bookkeeping */ }
    }
    return {
      ok: false,
      error: answered ? 'unknown_outcome' : 'send_failed',
      detail: answered
        ? 'The payment was sent but the answer could not be read, so we cannot tell whether the card was charged. '
          + 'Check with AppraisalScope before trying again — this one is deliberately left locked.'
        : detail,
    };
  }
}

/**
 * SEND THE BORROWER (AND THE LOAN OFFICER) THE VENDOR'S OWN INVOICE.
 *
 * ONE CALL PER ADDRESS, deliberately — see `cdg.buildSendInvoice` for why the
 * plural `notifications` array is not trusted to fan out. Each recipient's outcome
 * is reported separately, so "it went to the borrower and not to the officer" is a
 * thing the screen can actually say instead of one boolean for both.
 *
 * NO CLAIM AND NO LOCK: a second invoice email is a nuisance, not a second charge,
 * and locking it would mean a bounced first attempt could never be re-sent.
 */
async function sendInvoice(dbh, opts = {}) {
  const { orderId, emails, staffId = null, deps = {} } = opts;
  const order = await loadOrder(dbh, orderId);
  if (!order) return { ok: false, error: 'no_order' };

  const list = [...new Set((Array.isArray(emails) ? emails : [emails])
    .map((e) => String(e == null ? '' : e).trim().toLowerCase())
    .filter((e) => e && e.includes('@')))];
  if (!list.length) return { ok: false, error: 'no_recipient', detail: 'Nobody to send the invoice to.' };

  const transport = deps.transport || client;
  let ctx;
  try { ctx = deps.authContext || (await session.authContext()); }
  catch (e) { return { ok: false, error: 'send_failed', detail: String((e && e.message) || e) }; }

  const sent = [];
  const failed = [];
  for (const email of list) {
    try {
      const resp = await transport.write(cdg.buildSendInvoice({
        apiKey: ctx.apiKey,
        subdomain: order.sp_subdomain || ctx.subdomain,
        clientOrderNumber: order.client_order_number,
        spOrderNumber: order.sp_order_number,
        email,
      }), { label: 'SendInvoice' });
      const err = cdg.parseError(resp);
      if (err) failed.push({ email, reason: err.description || `status ${err.code}` });
      else sent.push(email);
    } catch (e) {
      failed.push({ email, reason: String((e && e.message) || e) });
    }
  }

  // The INSTRUCTION is recorded whenever at least one invoice actually went, so
  // the desk reads "to be paid by payment link" rather than nothing. It is NOT
  // recorded when every send failed — writing down a link nobody received is the
  // kind of confident-but-wrong note this table exists to stop.
  let intent = null;
  if (sent.length) {
    const noted = await require('../lib/appraisal/payment-intent').record({
      appId: order.application_id, vendor: 'nan', orderId, method: 'PAYMENT_LINK',
      staffId, note: `Invoice emailed to ${sent.join(', ')}`, dbc: dbh,
    });
    intent = noted.ok ? noted.intent : null;
  }

  return { ok: sent.length > 0, sent, failed, intent };
}

module.exports = {
  charge, sendInvoice, paymentState, referenceFor,
  // exported so the DB test can drive the pieces directly
  _internals: { loadCard, loadHolder, loadOrder, claimCharge, releaseCharge, recordCharge },
};
