-- 360 — Remember what a purchase advice document's visibility USED to be.
--
-- Designating a document as the purchase advice forces it staff-only (it names
-- the note buyer and the price the loan sold for). But the picker offers EVERY
-- document on the file, and before this column there was no way back: `UPDATE
-- documents SET visibility` existed in exactly ONE place in the whole codebase —
-- the forcing itself. A single mis-pick permanently hid a borrower's own
-- insurance policy or photo ID from their Documents list, their downloads and
-- their mentionables, recoverable only by hand-written SQL.
--
-- Recording the prior value lets the pointer moving away restore it, so the
-- confidentiality guarantee costs nothing that cannot be undone.
--
-- Idempotent.
ALTER TABLE purchasing_advice ADD COLUMN IF NOT EXISTS document_prior_visibility text;
