'use strict';
/**
 * LT PPE — scenario COVERAGE generators (MEGA plan §10.3). PURE: no DB, no network, no randomness
 * (deterministic, so a battery is reproducible). These complement scenario-matrix.buildMatrix (the
 * full cartesian product) with the three representative strategies §10.3 asks for:
 *
 *   Layer A — one-field goldens: from a baseline, change EXACTLY one field at a time across every
 *             enumerated option (one golden per option). The backbone.
 *   Layer B — numeric boundaries: below-min / min / mid / max / above-max, plus just-inside and
 *             just-outside every band edge (where the LLPA grid and eligibility flip).
 *   Layer C — pairwise (t-way): the smallest set where every VALUE PAIR from any two axes appears in
 *             at least one scenario — generated by an algorithm, never hand-listed.
 *
 * The caller supplies the axis VALUES (the investor's enumerated field options / band edges); this
 * module never invents a pricing band. Every scenario is tagged with `_probe` (what it exercises) and
 * `_layer` so a disagreement traces straight back to the scenario that provoked it (§10.4).
 *
 * LT-only. No RTL imports.
 */

// ---- Layer A: one-field goldens --------------------------------------------
/**
 * From `baseline`, emit one scenario per (field, option): baseline with exactly that field changed.
 * A leading baseline scenario is included. `opts.includeBaselineValue` (default true) keeps an option
 * even when it equals the baseline (a golden per option, as §10.3 says).
 */
function oneFieldGoldens(baseline = {}, axes = {}, opts = {}) {
  const includeBase = opts.includeBaselineValue !== false;
  const out = [{ ...baseline, _layer: 'A', _probe: 'baseline' }];
  for (const key of Object.keys(axes)) {
    const vals = Array.isArray(axes[key]) ? axes[key] : [];
    for (const v of vals) {
      if (!includeBase && baseline[key] === v) continue;
      out.push({ ...baseline, [key]: v, _layer: 'A', _probe: `${key}=${fmt(v)}` });
    }
  }
  return out;
}

// ---- Layer B: numeric boundaries -------------------------------------------
/**
 * Boundary probes for ONE numeric field on a baseline.
 *   spec: { min, max, mid?, edges?:[...], epsilon=1 }
 * Emits below-min (min-ε), min, mid (or midpoint), max, above-max (max+ε), and for each edge the
 * value just-below (edge-ε) and at the edge. Deduped by value; each tagged with its role.
 */
function boundaryScenarios(baseline = {}, field, spec = {}) {
  const eps = spec.epsilon == null ? 1 : spec.epsilon;
  const probes = [];
  const add = (val, role) => { if (typeof val === 'number' && Number.isFinite(val)) probes.push({ val, role }); };
  if (spec.min != null) { add(spec.min - eps, 'below-min'); add(spec.min, 'min'); }
  const mid = spec.mid != null ? spec.mid
    : (spec.min != null && spec.max != null ? Math.round((spec.min + spec.max) / 2) : null);
  if (mid != null) add(mid, 'mid');
  if (spec.max != null) { add(spec.max, 'max'); add(spec.max + eps, 'above-max'); }
  for (const e of (Array.isArray(spec.edges) ? spec.edges : [])) {
    add(e - eps, 'just-below-edge');
    add(e, 'at-edge');
  }
  // dedup by value, keep the first role seen
  const seen = new Set();
  const out = [];
  for (const p of probes) {
    if (seen.has(p.val)) continue;
    seen.add(p.val);
    out.push({ ...baseline, [field]: p.val, _layer: 'B', _probe: `${field}=${p.val} (${p.role})` });
  }
  return out;
}

// ---- Layer C: pairwise (t=2) -----------------------------------------------
function fmt(v) { return typeof v === 'object' ? JSON.stringify(v) : String(v); }
function pairTok(i, vi, j, vj) { return `${i}:${fmt(vi)}|${j}:${fmt(vj)}`; }

/**
 * Generate a pairwise (all-pairs) scenario set: every value pair from any two axes appears together in
 * at least one scenario. Deterministic greedy construction (ties broken by value order). `opts.base`
 * is merged under every case; `opts.maxCases` (default 5000) is a runaway backstop.
 * Returns { scenarios, pairsCovered, pairsTotal, complete }.
 */
function pairwise(axes = {}, opts = {}) {
  const base = opts.base || {};
  const maxCases = opts.maxCases == null ? 5000 : opts.maxCases;
  const keys = Object.keys(axes).filter((k) => Array.isArray(axes[k]) && axes[k].length > 0);

  // 0 or 1 axis: no pairs exist — emit each value once (or the base alone).
  if (keys.length === 0) return { scenarios: [{ ...base, _layer: 'C', _probe: 'base' }], pairsCovered: 0, pairsTotal: 0, complete: true };
  if (keys.length === 1) {
    const k = keys[0];
    return {
      scenarios: axes[k].map((v) => ({ ...base, [k]: v, _layer: 'C', _probe: `${k}=${fmt(v)}` })),
      pairsCovered: 0, pairsTotal: 0, complete: true,
    };
  }

  // Build the pair list (for seeding) and the uncovered token set (for O(1) membership).
  const pairList = [];
  const uncovered = new Set();
  for (let i = 0; i < keys.length; i += 1) {
    for (let j = i + 1; j < keys.length; j += 1) {
      for (const vi of axes[keys[i]]) for (const vj of axes[keys[j]]) {
        const tok = pairTok(i, vi, j, vj);
        pairList.push({ i, vi, j, vj, tok });
        uncovered.add(tok);
      }
    }
  }
  const pairsTotal = uncovered.size;

  // token for (axisA=vA, axisB=vB) in canonical lo<hi order
  const tokFor = (a, va, b, vb) => (a < b ? pairTok(a, va, b, vb) : pairTok(b, vb, a, va));

  const scenarios = [];
  while (uncovered.size > 0 && scenarios.length < maxCases) {
    // SEED from the first still-uncovered pair — guarantees this case covers >=1 pair (termination).
    let seed = null;
    for (const p of pairList) { if (uncovered.has(p.tok)) { seed = p; break; } }
    if (!seed) break;

    const combo = {};
    const assigned = [];
    combo[keys[seed.i]] = seed.vi; assigned.push(seed.i);
    combo[keys[seed.j]] = seed.vj; assigned.push(seed.j);

    // fill the remaining axes greedily: pick the value covering the most uncovered pairs with the
    // already-assigned axes (deterministic — first value wins a tie).
    for (let a = 0; a < keys.length; a += 1) {
      if (assigned.includes(a)) continue;
      let bestVal = axes[keys[a]][0];
      let bestCov = -1;
      for (const v of axes[keys[a]]) {
        let cov = 0;
        for (const b of assigned) if (uncovered.has(tokFor(a, v, b, combo[keys[b]]))) cov += 1;
        if (cov > bestCov) { bestCov = cov; bestVal = v; }
      }
      combo[keys[a]] = bestVal;
      assigned.push(a);
    }

    // mark every pair in this combo covered
    for (let i = 0; i < keys.length; i += 1) {
      for (let j = i + 1; j < keys.length; j += 1) uncovered.delete(pairTok(i, combo[keys[i]], j, combo[keys[j]]));
    }
    scenarios.push({ ...base, ...combo, _layer: 'C', _probe: `pairwise#${scenarios.length}` });
  }

  return { scenarios, pairsCovered: pairsTotal - uncovered.size, pairsTotal, complete: uncovered.size === 0 };
}

module.exports = { oneFieldGoldens, boundaryScenarios, pairwise, _internals: { pairTok, fmt } };
