'use strict';

/**
 * DOCUMENT DOSSIER — the full story of ONE uploaded document.
 *
 * Owner-directed (2026-08-02): "Documents and exports … it's too vague, it just
 * says everywhere 'General upload'. We need to be more in detail what was
 * uploaded, to which condition was it uploaded, and what happened with that
 * document — was it accepted… all the details that is happening with this
 * document."
 *
 * The Documents & exports panel used to show a filename, a size, a date and a
 * one-word status. Everything else the system already knew about a document —
 * which condition it answered, which slot inside that condition, why that
 * condition exists, who reviewed it and when, what they said when they rejected
 * it, which version replaced it, whether it reached SharePoint, whether PILOT
 * could read it and what it found — was scattered across a dozen tables and
 * visible on no screen.
 *
 * This module is the PURE half: it owns the WORDING and the SHAPING. It never
 * touches the database, never throws on a missing field, and never invents a
 * fact — an unknown value renders as the honest "—"/null rather than a guess.
 * The route (src/routes/staff.js `GET /documents/:id/dossier`) does the reading
 * and hands the rows here; the portal renders what comes back.
 *
 * THE THREE QUESTIONS the panel must answer for every document:
 *   1. WHERE did it land?      → describePlacement()
 *   2. WHY was it uploaded?    → describePurpose()
 *   3. WHAT happened to it?    → buildTimeline()
 */

// ---------------------------------------------------------------------------
// Vocabulary. One place, so the server, the portal and the tests agree.
// ---------------------------------------------------------------------------

/* documents.source_type — HOW the document arrived. */
const SOURCE_TYPES = {
  borrower_upload:  { label: 'Borrower upload',      why: 'The borrower uploaded this from their portal.' },
  staff_upload:     { label: 'Staff upload',         why: 'Someone on the loan team filed this on the borrower’s behalf.' },
  chat_attachment:  { label: 'Chat attachment',      why: 'Sent as an attachment in a conversation on this file.' },
  document_request: { label: 'Requested document',   why: 'Uploaded in answer to a document the loan team asked for.' },
  condition:        { label: 'Condition evidence',   why: 'Uploaded as the evidence for a condition on this file.' },
  tpr:              { label: 'TPR / clean-file export', why: 'Generated by PILOT as part of the clean-file (TPR) export.' },
  post_closing:     { label: 'Post-closing document', why: 'Filed after the loan funded, as part of post-closing.' },
  system:           { label: 'Generated by PILOT',   why: 'PILOT produced this document itself — nobody uploaded it.' },
};

/* documents.doc_kind — WHAT the document is, when the system generated or
   classified it. Anything not listed is humanized rather than shown raw. */
const DOC_KINDS = {
  term_sheet:             'Term sheet',
  term_sheet_signed:      'Signed term sheet',
  esign_certificate:      'E-signature certificate',
  photo_id:               'Government photo ID',
  credit_pdf:             'Credit report (PDF)',
  credit_xml:             'Credit report (data file)',
  appraisal_pdf:          'Appraisal report',
  appraisal_photo:        'Appraisal photo',
  flood_determination:    'Flood determination certificate',
  rehab_budget_export:    'Scope of work / rehab budget export',
  track_record_doc:       'Track-record document',
  track_record_html:      'Track-record export',
  tpr_export:             'Clean-file (TPR) export',
  noo_affidavit:          'Non-owner-occupied affidavit',
  purchase_advice:        'Purchase advice',
  closing_correspondence: 'Closing correspondence',
  draw_request_signed:    'Signed draw request',
  draw_inspection_report: 'Draw inspection report',
};

/* documents.visibility — WHO can see it. */
const VISIBILITY = {
  borrower:   { label: 'Visible to the borrower', note: 'The borrower can see this document in their portal.' },
  staff_only: { label: 'Staff only',              note: 'Internal — the borrower never sees this document.' },
  internal:   { label: 'Internal',                note: 'Internal working file — not part of the borrower’s view.' },
};

/* documents.review_status — WHERE it stands. */
const REVIEW_STATUS = {
  pending:    { label: 'Awaiting review', tone: 'outstanding', note: 'Nobody has accepted or rejected this yet.' },
  accepted:   { label: 'Accepted',        tone: 'ok',          note: 'A reviewer accepted this document.' },
  rejected:   { label: 'Rejected',        tone: 'bad',         note: 'A reviewer rejected this document — it is in the file’s trash.' },
  superseded: { label: 'Replaced',        tone: 'muted',       note: 'A newer version replaced this document.' },
};

/* documents.sharepoint_mirror_status — the mirror state machine (db/220). */
const MIRROR_STATUS = {
  PENDING:     { label: 'Waiting to sync',   tone: 'outstanding' },
  IN_PROGRESS: { label: 'Syncing now',       tone: 'outstanding' },
  DONE:        { label: 'Synced',            tone: 'ok' },
  FAILED:      { label: 'Sync failed — will retry', tone: 'warn' },
  DEAD:        { label: 'Sync gave up',      tone: 'bad' },
  SKIPPED:     { label: 'Not mirrored',      tone: 'muted' },
};

/* documents.authenticity_level (db/237). */
const AUTHENTICITY = {
  high:       { label: 'Looks genuine',        tone: 'ok' },
  medium:     { label: 'Some signals missing', tone: 'warn' },
  low:        { label: 'Authenticity concerns', tone: 'bad' },
  unreadable: { label: 'Could not be checked', tone: 'muted' },
};

/* Audit actions that belong on a DOCUMENT's own history, with the wording the
   timeline shows. Anything else on the document lands via humanize(). */
const DOC_AUDIT = {
  upload_document:              { title: 'Uploaded',                 icon: '⬆️', tone: 'info' },
  upload_photo_id:              { title: 'Photo ID uploaded',        icon: '⬆️', tone: 'info' },
  upload_track_record_doc:      { title: 'Track-record document uploaded', icon: '⬆️', tone: 'info' },
  staff_upload_track_record_doc:{ title: 'Track-record document uploaded by staff', icon: '⬆️', tone: 'info' },
  accept_document:              { title: 'Accepted',                 icon: '✅', tone: 'ok' },
  accept_document_request_more: { title: 'Accepted — and one more document asked for', icon: '✅', tone: 'warn' },
  reject_document:              { title: 'Rejected',                 icon: '⛔', tone: 'bad' },
  delete_document:              { title: 'Deleted',                  icon: '🗑', tone: 'bad' },
  download_document:            { title: 'Downloaded',               icon: '⬇️', tone: 'muted' },
  ocr_document:                 { title: 'Text read off the document (OCR)', icon: '🔎', tone: 'info' },
  classify_document:            { title: 'Classified',               icon: '🏷', tone: 'info' },
  document_reclassified:        { title: 'Re-classified',            icon: '🏷', tone: 'info' },
};

const ACTOR_KIND = { borrower: 'the borrower', staff: 'staff', system: 'PILOT' };

// ---------------------------------------------------------------------------
// Small helpers. All total — never throw, never guess.
// ---------------------------------------------------------------------------

const str = (v) => (v == null ? '' : String(v));
const trimmed = (v) => str(v).trim();

/** `some_new_thing` → `Some new thing`. Used wherever a code has no wording. */
function humanize(code) {
  const s = trimmed(code).replace(/[_-]+/g, ' ').trim();
  if (!s) return '';
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function bytesLabel(n) {
  const b = Number(n);
  if (!isFinite(b) || b <= 0) return null;
  if (b < 1024) return `${b} B`;
  if (b < 1024 * 1024) return `${Math.round(b / 1024)} KB`;
  return `${(b / (1024 * 1024)).toFixed(1)} MB`;
}

/** A page range stored as an int[] pair — `[3, 9]` → "pages 3–9". */
function pageRangeLabel(range) {
  if (!Array.isArray(range) || !range.length) return null;
  const a = Number(range[0]);
  const b = Number(range.length > 1 ? range[1] : range[0]);
  if (!isFinite(a) || !isFinite(b)) return null;
  return a === b ? `page ${a}` : `pages ${a}–${b}`;
}

function sourceType(row) { return SOURCE_TYPES[trimmed(row && row.source_type)] || null; }
function visibility(row) { return VISIBILITY[trimmed(row && row.visibility)] || null; }
function reviewStatus(row) {
  return REVIEW_STATUS[trimmed(row && row.review_status) || 'pending'] || REVIEW_STATUS.pending;
}
function mirrorStatus(row) {
  const raw = trimmed(row && row.sharepoint_mirror_status).toUpperCase();
  if (MIRROR_STATUS[raw]) return { code: raw, ...MIRROR_STATUS[raw] };
  // No FSM row yet: fall back to the columns that encode it implicitly.
  if (row && row.sharepoint_backed_up_at) return { code: 'DONE', ...MIRROR_STATUS.DONE };
  if (row && row.sharepoint_skipped_reason) return { code: 'SKIPPED', ...MIRROR_STATUS.SKIPPED };
  if (row && Number(row.sharepoint_backup_attempts) > 0) return { code: 'FAILED', ...MIRROR_STATUS.FAILED };
  return { code: 'PENDING', ...MIRROR_STATUS.PENDING };
}
function authenticity(row) {
  const lvl = trimmed(row && row.authenticity_level).toLowerCase();
  if (!lvl) return null;
  const meta = AUTHENTICITY[lvl] || { label: humanize(lvl), tone: 'muted' };
  return { level: lvl, ...meta, score: row.authenticity_score == null ? null : Number(row.authenticity_score) };
}

/** SharePoint integrity is free-text with a stable prefix (`ok`, `mismatch…`). */
function integrityLabel(value) {
  const v = trimmed(value);
  if (!v) return null;
  if (/^ok\b/.test(v)) return { label: 'Verified byte-for-byte', tone: 'ok', raw: v };
  if (/^mismatch/.test(v)) return { label: 'Copy does not match the original', tone: 'bad', raw: v };
  if (/^source-suspect/.test(v)) return { label: 'Source file looks damaged', tone: 'bad', raw: v };
  if (/^malware/.test(v)) return { label: 'Flagged by malware scanning', tone: 'bad', raw: v };
  if (v === 'item-missing') return { label: 'Missing in SharePoint', tone: 'bad', raw: v };
  if (v === 'local-missing') return { label: 'Missing in PILOT’s storage', tone: 'bad', raw: v };
  return { label: humanize(v), tone: 'muted', raw: v };
}

// ---------------------------------------------------------------------------
// 0. TITLE — what this document is CALLED on the list.
// ---------------------------------------------------------------------------

/**
 * The document's identity line. The condition it answers comes first (that is
 * what a processor is looking for), then the kind of document, and only as a
 * LAST resort a generic phrase — and even that names how it arrived rather than
 * the old catch-all "General upload".
 *
 * `row.item_label` is the condition label the list query already joins in.
 */
function documentTitle(row) {
  const r = row || {};
  const item = trimmed(r.item_label);
  if (item) return item;
  const kind = trimmed(r.doc_kind);
  if (kind) return DOC_KINDS[kind] || humanize(kind);
  const src = sourceType(r);
  if (src && src.label !== 'Staff upload' && src.label !== 'Borrower upload') return src.label;
  if (r.track_record_id) return 'Track-record document';
  if (r.llc_id) return 'Vesting-entity document';
  // Truthful catch-all: it really is a loose file on the loan, and we say so.
  return 'Filed on the loan — not attached to a condition';
}

// ---------------------------------------------------------------------------
// 1. WHERE — the document's address inside the file.
// ---------------------------------------------------------------------------

/**
 * describePlacement(row) → { where, whereLabel, lines[], condition, unattached }
 *
 * `row` is the document joined with its condition (`cond_*` fields), entity
 * (`llc_name`) and track record (`track_record_label`). Everything is optional.
 *
 * `where` is the machine code: condition | entity | track_record | lead |
 * chat | file. `lines` are the human sentences the panel prints.
 */
function describePlacement(row) {
  const r = row || {};
  const lines = [];
  let where = 'file';
  let whereLabel = 'Filed on the loan';

  const condLabel = trimmed(r.cond_label) || trimmed(r.item_label);
  if (r.checklist_item_id && condLabel) {
    where = 'condition';
    whereLabel = `Condition — ${condLabel}`;
    lines.push(`Uploaded to the condition “${condLabel}”.`);
  } else if (r.track_record_id) {
    where = 'track_record';
    const t = trimmed(r.track_record_label);
    whereLabel = t ? `Track record — ${t}` : 'Track record';
    lines.push(t ? `Filed on the borrower’s track-record project “${t}”.`
                 : 'Filed on the borrower’s track record.');
  } else if (r.llc_id) {
    where = 'entity';
    const n = trimmed(r.llc_name);
    whereLabel = n ? `Vesting entity — ${n}` : 'Vesting entity';
    lines.push(n ? `Filed on the vesting entity “${n}” — it travels with the entity to every file it vests into.`
                 : 'Filed on the vesting entity — it travels with the entity to every file it vests into.');
  } else if (r.lead_id) {
    where = 'lead';
    whereLabel = 'Lead record';
    lines.push('Filed on the lead record, before there was a loan file.');
  } else if (trimmed(r.source_type) === 'chat_attachment') {
    where = 'chat';
    whereLabel = 'Conversation attachment';
    lines.push('Sent as an attachment in a conversation — not part of the review queue.');
  } else {
    lines.push('Filed on the loan itself — it is not attached to any condition, so nothing is waiting on it.');
  }

  const slot = trimmed(r.slot_label);
  if (slot) lines.push(`It fills the “${slot}” slot inside that item.`);

  const pages = pageRangeLabel(r.page_range);
  if (pages && r.source_document_id) lines.push(`Split out of a larger upload — ${pages} of the original packet.`);
  else if (pages) lines.push(`Covers ${pages} of the upload.`);

  const vis = visibility(r);
  if (vis) lines.push(vis.note);

  const condition = r.checklist_item_id ? {
    id: r.checklist_item_id,
    label: condLabel || null,
    status: trimmed(r.cond_status) || null,
    audience: trimmed(r.cond_audience) || null,
    phase: trimmed(r.cond_phase) || null,
    category: trimmed(r.cond_category) || null,
    itemKind: trimmed(r.cond_item_kind) || null,
    isGate: !!r.cond_is_gate,
    isRequired: !!r.cond_is_required,
    hint: trimmed(r.cond_hint) || null,
    borrowerHint: trimmed(r.cond_borrower_hint) || null,
    originKind: trimmed(r.cond_origin_kind) || null,
    originDetail: trimmed(r.cond_origin_detail) || null,
    signedOffAt: r.cond_signed_off_at || null,
    signedOffBy: trimmed(r.cond_signed_off_by_name) || null,
    waivedAt: r.cond_waived_at || null,
  } : null;

  return { where, whereLabel, lines, condition, unattached: where === 'file' };
}

// ---------------------------------------------------------------------------
// 2. WHY — the purpose of the upload.
// ---------------------------------------------------------------------------

/**
 * describePurpose(row) → { headline, why[], asked }
 *
 * The headline answers "what is this document FOR". `why` collects the
 * supporting sentences: the condition's own hint (the words the borrower was
 * shown), the reason the condition exists at all (its origin), and what
 * accepting it unblocks.
 */
function describePurpose(row) {
  const r = row || {};
  const p = describePlacement(r);
  const cond = p.condition;
  const why = [];

  let headline;
  if (cond && cond.label) {
    headline = cond.isGate
      ? `Evidence for the gate “${cond.label}” — the file cannot move on until this is satisfied.`
      : `Evidence for the condition “${cond.label}”.`;
  } else {
    const kind = trimmed(r.doc_kind);
    const src = sourceType(r);
    headline = kind && (DOC_KINDS[kind] || humanize(kind))
      ? `${DOC_KINDS[kind] || humanize(kind)} on this file.`
      : src ? src.why
      : 'Filed on this loan for the record.';
  }

  // The exact words the borrower (or the processor) was shown when asked.
  const asked = trimmed(cond && (cond.borrowerHint || cond.hint)) || null;
  if (asked) why.push(`What was asked for: ${asked}`);

  const src = sourceType(r);
  if (src) why.push(src.why);

  if (cond && cond.originKind) {
    const originWords = {
      auto: 'PILOT’s condition rules put this condition on the file automatically.',
      rule: 'PILOT’s condition rules put this condition on the file automatically.',
      manual: 'A member of the loan team added this condition by hand.',
      template: 'This condition comes from the standard condition library for this program.',
      note_buyer: 'The capital provider requires this condition.',
      investor: 'The capital provider requires this condition.',
      exception: 'This condition came out of a policy exception on the file.',
    };
    const w = originWords[cond.originKind] || `Condition origin: ${humanize(cond.originKind)}.`;
    why.push(cond.originDetail ? `${w} (${cond.originDetail})` : w);
  }

  if (cond && cond.isRequired) why.push('The condition is REQUIRED — it cannot simply be waived away.');

  if (r.track_record_id) why.push('It also backs a project on the borrower’s track record, which their experience count is built from.');
  if (r.llc_id) why.push('Rejecting it un-verifies the vesting entity, because the verification stood on this document.');

  return { headline, why, asked };
}

// ---------------------------------------------------------------------------
// 3. WHAT HAPPENED — the merged timeline.
// ---------------------------------------------------------------------------

const ev = (at, code, title, opts) => ({
  at: at || null,
  code,
  title,
  icon: (opts && opts.icon) || '•',
  tone: (opts && opts.tone) || 'info',
  detail: (opts && opts.detail) || null,
  actor: (opts && opts.actor) || null,
  // The real human behind a borrower-view session, when there was one.
  impersonator: (opts && opts.impersonator) || null,
  source: (opts && opts.source) || 'document',
});

function actorLabel(kind, name) {
  const n = trimmed(name);
  if (n) return n;
  return ACTOR_KIND[trimmed(kind)] || (trimmed(kind) ? humanize(kind) : null);
}

/**
 * buildTimeline(input) → [event] in CHRONOLOGICAL order (oldest first — a
 * document's history reads as a story, not as a news feed).
 *
 * Every input list is optional. The builder is deliberately forgiving: a caller
 * that cannot read one of the side tables (the AI tables are env-gated, the
 * pipeline tables ship behind a flag) simply passes nothing and the timeline is
 * shorter — never broken.
 *
 * DE-DUPLICATION: the document row and the audit log record the SAME accept /
 * reject event. The audit row is richer (it names the actor), so when an audit
 * row for a verdict exists we do not also derive one from `reviewed_at`.
 */
function buildTimeline(input) {
  const i = input || {};
  const doc = i.doc || {};
  const audits = Array.isArray(i.audits) ? i.audits : [];
  const versions = Array.isArray(i.versions) ? i.versions : [];
  const extractions = Array.isArray(i.extractions) ? i.extractions : [];
  const findings = Array.isArray(i.findings) ? i.findings : [];
  const jobs = Array.isArray(i.jobs) ? i.jobs : [];
  const syncRows = Array.isArray(i.syncRows) ? i.syncRows : [];
  const lifecycle = Array.isArray(i.lifecycle) ? i.lifecycle : [];

  const out = [];

  // ---- 1. It arrived ------------------------------------------------------
  const uploadedByAudit = audits.some((a) => /^upload/.test(trimmed(a && a.action)));
  if (!uploadedByAudit) {
    const who = actorLabel(doc.uploaded_by_kind, doc.uploaded_by_name);
    const bits = [bytesLabel(doc.size_bytes), trimmed(doc.content_type) || null].filter(Boolean);
    out.push(ev(doc.created_at, 'uploaded', 'Uploaded', {
      icon: '⬆️', tone: 'info',
      actor: who,
      detail: [trimmed(doc.filename), bits.join(' · ')].filter(Boolean).join(' — ') || null,
    }));
  }

  // ---- 2. Everything a human did to it (audit log) -----------------------
  for (const a of audits) {
    const action = trimmed(a && a.action);
    if (!action) continue;
    const meta = DOC_AUDIT[action] || { title: humanize(action), icon: '•', tone: 'info' };
    const d = (a && a.detail) || {};
    const bits = [];
    if (d.reason) bits.push(`Reason: ${d.reason}`);
    if (d.note) bits.push(`Note to the borrower: ${d.note}`);
    if (d.engine) bits.push(`Engine: ${d.engine}`);
    if (d.pageCount) bits.push(`${d.pageCount} page${Number(d.pageCount) === 1 ? '' : 's'}`);
    if (d.filename && action !== 'upload_document') bits.push(String(d.filename));
    if (d.wasMirrored) bits.push('It had already been mirrored to SharePoint.');
    // ON-BEHALF-OF. An action taken inside a borrower-view session is recorded
    // under the BORROWER's identity — which is correct, that is who the session
    // ran as — so naming only the actor tells the reader a borrower did
    // something a staff member did. Name the real human, and mark the row, so
    // it can never be read as the borrower's own act.
    const onBehalf = trimmed(a.impersonator_name);
    if (onBehalf) bits.unshift(`⚠️ Done by ${onBehalf} while signed in as this borrower.`);
    out.push(ev(a.created_at, action, meta.title, {
      icon: meta.icon, tone: onBehalf ? 'warn' : meta.tone, source: 'audit',
      actor: actorLabel(a.actor_kind, a.actor_name),
      impersonator: onBehalf || null,
      detail: bits.join(' · ') || null,
    }));
  }

  // ---- 3. The verdict, when no audit row carries it ----------------------
  const verdictInAudit = audits.some((a) => /^(accept_document|reject_document)/.test(trimmed(a && a.action)));
  const rs = trimmed(doc.review_status);
  if (!verdictInAudit && doc.reviewed_at && (rs === 'accepted' || rs === 'rejected')) {
    out.push(ev(doc.reviewed_at, rs === 'accepted' ? 'accept_document' : 'reject_document',
      rs === 'accepted' ? 'Accepted' : 'Rejected', {
        icon: rs === 'accepted' ? '✅' : '⛔',
        tone: rs === 'accepted' ? 'ok' : 'bad',
        actor: trimmed(doc.reviewed_by_name) || null,
        detail: rs === 'rejected' && trimmed(doc.rejection_reason) ? `Reason: ${doc.rejection_reason}` : null,
      }));
  }

  // ---- 4. Version chain ---------------------------------------------------
  for (const v of versions) {
    if (!v) continue;
    if (trimmed(v.relation) === 'replaced_by') {
      out.push(ev(v.created_at, 'superseded', 'Replaced by a newer version', {
        icon: '🔁', tone: 'muted',
        detail: trimmed(v.filename) ? `Replaced by “${v.filename}”.` : null,
      }));
    } else if (trimmed(v.relation) === 'replaces') {
      out.push(ev(doc.created_at, 'replaces', 'Filed as a replacement', {
        icon: '🔁', tone: 'info',
        detail: trimmed(v.filename) ? `It replaced the earlier “${v.filename}”.` : null,
      }));
    }
  }
  // A superseded document with no visible successor still says so.
  if (rs === 'superseded' && !versions.some((v) => v && trimmed(v.relation) === 'replaced_by')) {
    out.push(ev(doc.reviewed_at || doc.created_at, 'superseded', 'Replaced by a newer version',
      { icon: '🔁', tone: 'muted' }));
  }

  // ---- 5. PILOT read it ---------------------------------------------------
  for (const x of extractions) {
    if (!x) continue;
    const type = trimmed(x.doc_type);
    const bits = [];
    if (x.confidence) bits.push(`Confidence: ${x.confidence}`);
    if (x.page_count) bits.push(`${x.page_count} page${Number(x.page_count) === 1 ? '' : 's'}`);
    if (x.ocr_engine) bits.push(`OCR: ${x.ocr_engine}`);
    if (x.ai_model) bits.push(`Model: ${x.ai_model}`);
    if (trimmed(x.status) === 'error' && x.reason) bits.push(`Why it failed: ${x.reason}`);
    const failed = trimmed(x.status) === 'error';
    out.push(ev(x.created_at, failed ? 'read_failed' : 'read', failed
      ? 'PILOT could not read the document'
      : `PILOT read the document${type ? ` as ${humanize(type).toLowerCase()}` : ''}`, {
      icon: failed ? '⚠️' : '🤖',
      tone: failed ? 'warn' : 'info',
      actor: 'PILOT',
      detail: bits.join(' · ') || null,
      source: 'ai',
    }));
  }

  // ---- 6. What that read raised ------------------------------------------
  for (const f of findings) {
    if (!f) continue;
    const sev = trimmed(f.severity) || 'info';
    out.push(ev(f.created_at, 'finding', `PILOT raised a ${sev} finding`, {
      icon: sev === 'fatal' ? '🚨' : sev === 'warning' ? '⚠️' : 'ℹ️',
      tone: sev === 'fatal' ? 'bad' : sev === 'warning' ? 'warn' : 'info',
      actor: 'PILOT',
      detail: [trimmed(f.title) || humanize(f.code),
        f.doc_value != null && f.file_value != null ? `Document says “${f.doc_value}”, the file says “${f.file_value}”.` : null,
      ].filter(Boolean).join(' — ') || null,
      source: 'ai',
    }));
    if (f.resolved_at) {
      out.push(ev(f.resolved_at, 'finding_resolved', `Finding ${trimmed(f.status) || 'resolved'}`, {
        icon: '☑️', tone: 'ok',
        actor: trimmed(f.resolved_by_name) || null,
        detail: [trimmed(f.title) || humanize(f.code), trimmed(f.resolution_note) || null].filter(Boolean).join(' — ') || null,
        source: 'ai',
      }));
    }
  }

  // ---- 7. The processing pipeline ----------------------------------------
  for (const j of jobs) {
    if (!j) continue;
    out.push(ev(j.created_at, 'job_queued', 'Queued for processing', {
      icon: '⏳', tone: 'muted', actor: 'PILOT', source: 'pipeline',
      detail: trimmed(j.document_family) ? `Routed as ${humanize(j.document_family).toLowerCase()}.` : null,
    }));
    const st = trimmed(j.status);
    if (['completed', 'failed_terminal', 'failed_retryable', 'cancelled', 'manual_review'].includes(st)) {
      const done = st === 'completed';
      out.push(ev(j.updated_at || j.created_at, `job_${st}`,
        done ? 'Processing finished'
          : st === 'manual_review' ? 'Sent for manual review'
          : st === 'cancelled' ? 'Processing cancelled'
          : 'Processing failed', {
          icon: done ? '✅' : st === 'manual_review' ? '👀' : '⚠️',
          tone: done ? 'ok' : st === 'manual_review' ? 'warn' : 'bad',
          actor: 'PILOT', source: 'pipeline',
          detail: [trimmed(j.last_error) || null,
            j.attempts ? `Attempt ${j.attempts}` : null].filter(Boolean).join(' · ') || null,
        }));
    }
  }

  // ---- 8. SharePoint ------------------------------------------------------
  if (doc.sharepoint_backed_up_at) {
    out.push(ev(doc.sharepoint_backed_up_at, 'sp_synced', 'Synced to SharePoint', {
      icon: '☁️', tone: 'ok', actor: 'PILOT', source: 'sharepoint',
      detail: doc.sharepoint_version ? `Version ${doc.sharepoint_version} in SharePoint.` : null,
    }));
  }
  if (doc.sharepoint_stamped_at) {
    out.push(ev(doc.sharepoint_stamped_at, 'sp_stamped', 'Filed under the loan’s SharePoint folder', {
      icon: '🏷', tone: 'muted', actor: 'PILOT', source: 'sharepoint',
    }));
  }
  if (doc.sharepoint_verified_at) {
    const integ = integrityLabel(doc.sharepoint_integrity);
    out.push(ev(doc.sharepoint_verified_at, 'sp_verified', 'SharePoint copy checked', {
      icon: integ && integ.tone === 'ok' ? '🛡' : '⚠️',
      tone: (integ && integ.tone) || 'muted',
      actor: 'PILOT', source: 'sharepoint',
      detail: integ ? integ.label : null,
    }));
  }
  if (doc.sharepoint_backup_error && doc.sharepoint_backup_attempted_at) {
    out.push(ev(doc.sharepoint_backup_attempted_at, 'sp_failed', 'SharePoint sync failed', {
      icon: '⚠️', tone: 'warn', actor: 'PILOT', source: 'sharepoint',
      detail: [trimmed(doc.sharepoint_backup_error),
        doc.sharepoint_backup_attempts ? `${doc.sharepoint_backup_attempts} attempt${Number(doc.sharepoint_backup_attempts) === 1 ? '' : 's'}` : null,
      ].filter(Boolean).join(' · ') || null,
    }));
  }
  if (doc.sharepoint_dead_reason) {
    out.push(ev(doc.sharepoint_next_attempt_at || doc.sharepoint_backup_attempted_at, 'sp_dead',
      'SharePoint sync gave up', {
        icon: '🛑', tone: 'bad', actor: 'PILOT', source: 'sharepoint',
        detail: trimmed(doc.sharepoint_dead_reason) || null,
      }));
  }
  if (doc.sharepoint_skipped_reason) {
    out.push(ev(doc.sharepoint_backup_attempted_at || doc.created_at, 'sp_skipped',
      'Deliberately not mirrored to SharePoint', {
        icon: '⊘', tone: 'muted', actor: 'PILOT', source: 'sharepoint',
        detail: trimmed(doc.sharepoint_skipped_reason) || null,
      }));
  }

  // ---- 9. Pushed OUT to an integration -----------------------------------
  // A DOCUMENT's outbound push is recorded per-integration (`sitewire_document_links`
  // today), NOT on the generic `sync_queue` — nothing ever enqueues a document
  // there, so reading that queue here would be permanently, silently empty.
  for (const s of syncRows) {
    if (!s) continue;
    const st = trimmed(s.status);
    const done = st === 'pushed' || st === 'verified' || st === 'done';
    const failed = st === 'failed' || st === 'error';
    const what = trimmed(s.which) ? ` (${humanize(s.which).toLowerCase()})` : '';
    out.push(ev(s.at || s.updated_at || s.created_at, `push_${st || 'queued'}`,
      done ? `Sent to the draw system${what}`
        : failed ? `Sending to the draw system failed${what}`
        : `Queued to send to the draw system${what}`, {
        icon: done ? '🔗' : failed ? '⚠️' : '⏳',
        tone: done ? 'ok' : failed ? 'bad' : 'muted',
        actor: trimmed(s.pushed_by_name) || 'PILOT', source: 'sync',
        detail: [trimmed(s.sitewire_document_name) || null, trimmed(s.last_error) || null]
          .filter(Boolean).join(' · ') || null,
      }));
  }

  // ---- 9b. DID IT ANSWER THE CONDITION IT WAS UPLOADED TO? ---------------
  // The most on-point record there is for "what was the purpose of this
  // document" — PILOT's per-requirement read of whether it actually cures.
  const PROOF = {
    satisfied: { title: 'PILOT read it as answering the condition', icon: '☑️', tone: 'ok' },
    partially_satisfied: { title: 'PILOT read it as only PARTLY answering the condition', icon: '◐', tone: 'warn' },
    not_satisfied: { title: 'PILOT read it as NOT answering the condition', icon: '⛔', tone: 'bad' },
    creates_new_finding: { title: 'It answers the condition but raised a new issue', icon: '⚠️', tone: 'warn' },
    unable_to_determine: { title: 'PILOT could not tell whether it answers the condition', icon: '❔', tone: 'muted' },
  };
  for (const p of (Array.isArray(i.proofs) ? i.proofs : [])) {
    if (!p) continue;
    const meta = PROOF[trimmed(p.result)]
      || { title: `Checked against the condition — ${humanize(p.result)}`, icon: '❔', tone: 'muted' };
    const reqs = Array.isArray(p.requirements_json) ? p.requirements_json : [];
    const missing = reqs.filter((r) => r && trimmed(r.status) && trimmed(r.status) !== 'satisfied')
      .map((r) => trimmed(r.label)).filter(Boolean);
    out.push(ev(p.created_at, 'clearance_proof', meta.title, {
      icon: meta.icon, tone: meta.tone, actor: 'PILOT', source: 'ai',
      detail: [trimmed(p.reviewer_summary) || null,
        missing.length ? `Still missing: ${missing.join(', ')}` : null,
        trimmed(p.recommended_action) ? `Suggested next step: ${humanize(p.recommended_action).toLowerCase()}` : null,
      ].filter(Boolean).join('\n') || null,
    }));
  }

  // ---- 9c. What PILOT proposed off the back of it ------------------------
  for (const s of (Array.isArray(i.suggestions) ? i.suggestions : [])) {
    if (!s) continue;
    const sev = trimmed(s.severity);
    out.push(ev(s.created_at, 'suggestion', 'PILOT suggested something from this document', {
      icon: '💡', tone: sev === 'fatal' ? 'bad' : sev === 'warning' ? 'warn' : 'info',
      actor: 'PILOT', source: 'ai',
      detail: [trimmed(s.title) || null, trimmed(s.body) ? String(s.body).slice(0, 300) : null]
        .filter(Boolean).join(' — ') || null,
    }));
    if (s.decided_at) {
      out.push(ev(s.decided_at, 'suggestion_decided',
        `A human ${humanize(s.status).toLowerCase()} PILOT's suggestion`, {
          icon: '👤', tone: 'ok', actor: trimmed(s.decided_by_name) || null, source: 'ai',
          detail: [trimmed(s.title) || null, trimmed(s.status_reason) || null].filter(Boolean).join(' — ') || null,
        }));
    }
  }

  // ---- 9d. HOW it was read — which engine, why, and what it cost ---------
  for (const r of (Array.isArray(i.routes) ? i.routes : [])) {
    if (!r) continue;
    const failed = trimmed(r.outcome) === 'failed';
    const bits = [
      trimmed(r.reason) || null,
      r.confidence == null ? null : `confidence ${Number(r.confidence).toFixed(2)}`,
      trimmed(r.challenger_provider) ? `double-checked against ${r.challenger_provider}` : null,
      r.latency_ms ? `${r.latency_ms}ms` : null,
      r.cost_cents ? `$${(Number(r.cost_cents) / 100).toFixed(2)}` : null,
    ].filter(Boolean);
    out.push(ev(r.created_at, failed ? 'route_failed' : 'route',
      failed ? `The reader failed on this document (${trimmed(r.provider) || 'unknown engine'})`
        : `Routed to ${trimmed(r.provider) || 'a reader'}${trimmed(r.service) ? ` · ${r.service}` : ''} to be read`, {
        icon: failed ? '⚠️' : '🧭', tone: failed ? 'warn' : 'muted',
        actor: 'PILOT', source: 'ai', detail: bits.join(' · ') || null,
      }));
  }

  // ---- 10. Packet lifecycle (split / merge / reclassify) -----------------
  for (const l of lifecycle) {
    if (!l) continue;
    const t = trimmed(l.event_type);
    if (!t) continue;
    out.push(ev(l.created_at, `lifecycle_${t}`, humanize(t), {
      icon: '📄', tone: 'info', source: 'lifecycle',
      actor: actorLabel(l.actor_kind, l.actor_name),
      detail: l.detail && typeof l.detail === 'object' && l.detail.note ? String(l.detail.note) : null,
    }));
  }

  // ---- 11. Authenticity ---------------------------------------------------
  if (doc.authenticity_checked_at) {
    const a = authenticity(doc);
    out.push(ev(doc.authenticity_checked_at, 'authenticity', 'Authenticity checked', {
      icon: a && a.tone === 'bad' ? '🚨' : '🔍',
      tone: (a && a.tone) || 'muted',
      actor: 'PILOT', source: 'ai',
      detail: a ? [a.label, a.score == null ? null : `score ${a.score}`].filter(Boolean).join(' · ') : null,
    }));
  }

  // Chronological. Rows with no timestamp sink to the bottom rather than
  // pretending to be the oldest thing that ever happened.
  const ts = (e) => {
    const v = e && e.at ? Date.parse(e.at) : NaN;
    return isFinite(v) ? v : Infinity;
  };
  return out.sort((a, b) => ts(a) - ts(b));
}

// ---------------------------------------------------------------------------
// The whole dossier, assembled. Pure: the route hands over the rows it read.
// ---------------------------------------------------------------------------

/* WHAT the reader was actually doing, from the URL they hit. A refusal is kept
   deliberately — "someone tried to open this and was turned away" is exactly
   the kind of thing an audit is looking for. */
function accessVerb(method, path, status) {
  const p = trimmed(path).toLowerCase();
  const denied = Number(status) === 403 || Number(status) === 401;
  let what = 'Opened the document';
  if (/\/download/.test(p)) what = /inline=1/.test(p) ? 'Previewed the document' : 'Downloaded the document';
  else if (/\/dossier/.test(p)) what = 'Looked at this history';
  else if (/\/ocr/.test(p)) what = 'Ran text recognition on it';
  else if (/\/review/.test(p)) what = 'Reviewed it';
  else if (trimmed(method).toUpperCase() === 'DELETE') what = 'Tried to delete it';
  return denied ? `${what} — REFUSED` : what;
}

/**
 * The access ledger. Built from the request log (which carries the IP and the
 * outcome of every attempt, including refusals) and topped up from the audit
 * log's own `download_document` rows so a document predating the request log
 * still shows its downloads.
 */
function buildAccess(requests, audits) {
  const out = [];
  for (const r of (Array.isArray(requests) ? requests : [])) {
    if (!r) continue;
    out.push({
      at: r.at || null,
      who: trimmed(r.actor_email) || (trimmed(r.actor_kind) ? humanize(r.actor_kind) : 'unknown'),
      role: trimmed(r.actor_role) || null,
      what: accessVerb(r.method, r.path, r.status),
      status: r.status == null ? null : Number(r.status),
      ip: r.ip || null,
      denied: Number(r.status) === 403 || Number(r.status) === 401,
      impersonator: trimmed(r.impersonator_name) || null,
    });
  }
  const seen = new Set(out.map((a) => `${a.at}`));
  for (const a of (Array.isArray(audits) ? audits : [])) {
    if (!a || trimmed(a.action) !== 'download_document') continue;
    if (seen.has(`${a.created_at}`)) continue;
    out.push({
      at: a.created_at || null,
      who: trimmed(a.actor_name) || (ACTOR_KIND[trimmed(a.actor_kind)] || 'unknown'),
      role: null, what: 'Downloaded the document', status: 200,
      ip: a.ip_address || null, denied: false,
      impersonator: trimmed(a.impersonator_name) || null,
    });
  }
  return out.sort((x, y) => new Date(y.at || 0) - new Date(x.at || 0)).slice(0, 100);
}

/**
 * buildDossier(input) → the object the portal renders.
 *
 * Nothing here fails on a missing side-table: an empty list is simply a shorter
 * dossier. That matters because half the inputs are env-gated features.
 */
function buildDossier(input) {
  const i = input || {};
  const doc = i.doc || {};
  const placement = describePlacement(doc);
  const purpose = describePurpose(doc);
  const timeline = buildTimeline(i);
  const rs = reviewStatus(doc);
  const mirror = mirrorStatus(doc);
  const auth = authenticity(doc);

  return {
    id: doc.id || null,
    title: documentTitle(doc),
    filename: trimmed(doc.filename) || null,
    identity: {
      filename: trimmed(doc.filename) || null,
      kind: trimmed(doc.doc_kind) ? (DOC_KINDS[trimmed(doc.doc_kind)] || humanize(doc.doc_kind)) : null,
      kindCode: trimmed(doc.doc_kind) || null,
      contentType: trimmed(doc.content_type) || null,
      size: bytesLabel(doc.size_bytes),
      sizeBytes: doc.size_bytes == null ? null : Number(doc.size_bytes),
      sha256: trimmed(doc.sha256) || null,
      pages: pageRangeLabel(doc.page_range),
      splitFromId: doc.source_document_id || null,
      uploadedAt: doc.created_at || null,
      uploadedBy: actorLabel(doc.uploaded_by_kind, doc.uploaded_by_name),
      uploadedByKind: trimmed(doc.uploaded_by_kind) || null,
      arrivedAs: sourceType(doc) ? sourceType(doc).label : null,
      visibility: visibility(doc) ? visibility(doc).label : null,
      isCurrent: doc.is_current !== false,
    },
    placement,
    purpose,
    review: {
      status: trimmed(doc.review_status) || 'pending',
      label: rs.label,
      tone: rs.tone,
      note: rs.note,
      reviewedAt: doc.reviewed_at || null,
      reviewedBy: trimmed(doc.reviewed_by_name) || null,
      rejectionReason: trimmed(doc.rejection_reason) || null,
    },
    storage: {
      provider: trimmed(doc.storage_provider) || null,
      mirror,
      webUrl: trimmed(doc.sharepoint_web_url) || null,
      syncedAt: doc.sharepoint_backed_up_at || null,
      verifiedAt: doc.sharepoint_verified_at || null,
      integrity: integrityLabel(doc.sharepoint_integrity),
      attempts: doc.sharepoint_backup_attempts == null ? null : Number(doc.sharepoint_backup_attempts),
      error: trimmed(doc.sharepoint_backup_error) || null,
      deadReason: trimmed(doc.sharepoint_dead_reason) || null,
      skippedReason: trimmed(doc.sharepoint_skipped_reason) || null,
      nextAttemptAt: doc.sharepoint_next_attempt_at || null,
    },
    authenticity: auth,
    // What this document IS elsewhere in the system — the credit report, the
    // appraisal, an executed signature package, the flood certificate…
    roles: (Array.isArray(i.roles) ? i.roles : []).filter(Boolean),
    // THE ACCESS LEDGER — who opened, previewed or downloaded it, when, and
    // from where. A regulated file has to be able to answer this, and it is
    // deliberately NOT folded into the timeline: a busy document produces
    // hundreds of views and would drown its own story.
    access: buildAccess(i.access, i.audits),
    versions: Array.isArray(i.versions) ? i.versions : [],
    timeline,
    counts: {
      events: timeline.length,
      findings: (Array.isArray(i.findings) ? i.findings : []).length,
      openFindings: (Array.isArray(i.findings) ? i.findings : [])
        .filter((f) => f && trimmed(f.status) === 'open').length,
      versions: (Array.isArray(i.versions) ? i.versions : []).length,
    },
  };
}

module.exports = {
  SOURCE_TYPES, DOC_KINDS, VISIBILITY, REVIEW_STATUS, MIRROR_STATUS, AUTHENTICITY, DOC_AUDIT,
  documentTitle, describePlacement, describePurpose, buildTimeline, buildDossier,
  integrityLabel, mirrorStatus, authenticity, reviewStatus, buildAccess,
  _internals: { humanize, bytesLabel, pageRangeLabel, actorLabel, accessVerb },
};
