'use strict';
/**
 * ZIP → STATE / COUNTY / COUNTY-FIPS lookup for the LT Lender Price DSCR pricer.
 *
 * WHY THIS EXISTS: pricing is ZIP-driven. The vendor's own screen takes a 5-digit ZIP and fills in
 * the state, the county name and the county FIPS before it searches; our connector demanded all of
 * them from the caller and refused an incomplete location. That is safe but not equivalent — a
 * caller quoting "Purchase, 760 FICO, $400k loan, 75% LTV, ZIP 11211" could not be served.
 *
 * WHY A TABLE, NOT A GEOCODER CALL: a quote must not depend on an outside service being reachable,
 * and the Census ADDRESS geocoder cannot answer a bare ZIP at all (it matches address ranges — a
 * lone ZIP returns no match, verified). The dataset is the Census Bureau's own ZCTA-to-county
 * relationship file, generated by scripts/build-lt-zip-county.js and committed, so this module is
 * PURE + OFFLINE: no network, no database, safe inside the pure test suites.
 *
 * THE ONE HONEST LIMITATION, surfaced rather than hidden: a ZIP is not a county. 9,452 of the 33,791
 * ZIPs here (28%) genuinely span more than one county, so for those "the ZIP" does not determine the
 * answer. We resolve the DOMINANT county (largest land overlap — the vendor's screen must likewise
 * pick one) and return `split: true` so the caller is TOLD it was inferred and can override it by
 * supplying countyFps explicitly. A sliver overlap (>=99% of the ZIP's land in one county) is a
 * boundary artifact and is not reported as a split.
 *
 * A ZIP that is not in the table (a PO-box-only ZIP has no ZCTA) returns null — the caller then
 * refuses the request rather than guessing a county.
 *
 * LT-only. No RTL imports.
 */
const DATA = require('./zip-county.json');

// Fixed-width records: zip(5) + countyRef(4) + splitFlag(1). Parsed lazily on first lookup so
// requiring this module costs nothing until a ZIP is actually resolved.
const REC = 10;
let INDEX = null; // Map<zip, {fips, countyName, split}>

// State FIPS prefix -> USPS state code. Derived from the county FIPS itself, so a ZIP resolves its
// state without a second table to keep in step.
const STATE_BY_FIPS = {
  '01': 'AL', '02': 'AK', '04': 'AZ', '05': 'AR', '06': 'CA', '08': 'CO', '09': 'CT', '10': 'DE',
  '11': 'DC', '12': 'FL', '13': 'GA', '15': 'HI', '16': 'ID', '17': 'IL', '18': 'IN', '19': 'IA',
  '20': 'KS', '21': 'KY', '22': 'LA', '23': 'ME', '24': 'MD', '25': 'MA', '26': 'MI', '27': 'MN',
  '28': 'MS', '29': 'MO', '30': 'MT', '31': 'NE', '32': 'NV', '33': 'NH', '34': 'NJ', '35': 'NM',
  '36': 'NY', '37': 'NC', '38': 'ND', '39': 'OH', '40': 'OK', '41': 'OR', '42': 'PA', '44': 'RI',
  '45': 'SC', '46': 'SD', '47': 'TN', '48': 'TX', '49': 'UT', '50': 'VT', '51': 'VA', '53': 'WA',
  '54': 'WV', '55': 'WI', '56': 'WY',
  // Territories the Census file carries. Lender Price's own state list governs eligibility; this
  // only reports what the ZIP IS, and the caller's state validation still applies.
  '60': 'AS', '66': 'GU', '69': 'MP', '72': 'PR', '78': 'VI',
};

// "Kings County" -> "Kings". Lender Price's captured requests carry the bare county name
// (countyName "Los Angeles"), not the Census NAMELSAD form.
function bareCountyName(namelsad) {
  return String(namelsad || '').replace(/\s+(County|Parish|Borough|Census Area|Municipality|City and Borough|Municipio)$/i, '').trim();
}

function buildIndex() {
  const m = new Map();
  const zips = DATA.zips || '';
  const counties = DATA.counties || [];
  for (let i = 0; i + REC <= zips.length; i += REC) {
    const zip = zips.slice(i, i + 5);
    const ref = Number(zips.slice(i + 5, i + 9));
    const split = zips[i + 9] === '1';
    const entry = counties[ref];
    if (!entry) continue;
    const bar = entry.indexOf('|');
    const fips = entry.slice(0, bar);
    m.set(zip, { fips, countyName: bareCountyName(entry.slice(bar + 1)), split });
  }
  return m;
}

/**
 * Resolve a 5-digit ZIP. Returns { zip, state, countyFps, countyName, split } or null when the ZIP
 * is unknown (never a guess). PURE — no network, no database, never throws.
 */
function lookupZip(zip) {
  const z = String(zip == null ? '' : zip).trim();
  if (!/^\d{5}$/.test(z)) return null;
  if (!INDEX) INDEX = buildIndex();
  const hit = INDEX.get(z);
  if (!hit) return null;
  const state = STATE_BY_FIPS[hit.fips.slice(0, 2)] || null;
  if (!state) return null; // a county whose state we cannot name is not a usable location
  return { zip: z, state, countyFps: hit.fips, countyName: hit.countyName, split: hit.split };
}

/**
 * Fill a scenario's location from its ZIP, treating anything the CALLER supplied as an ASSERTION
 * (audit §26.3 rule 3): we never overwrite a supplied value, and a supplied value that CONTRADICTS
 * the ZIP is reported as a conflict for the route to reject — silently preferring one side is how a
 * loan gets priced in the wrong county.
 *
 * Returns { ok:true, location, filled[], split } or { ok:false, code, field, message }.
 * `location` carries ONLY the fields worth writing back; the caller merges it over the scenario.
 * A scenario with no ZIP is not this module's business — it returns ok with nothing filled.
 */
function enrichLocation(sc = {}) {
  const zip = String(sc && sc.zip != null ? sc.zip : '').trim();
  if (!zip) return { ok: true, location: {}, filled: [], split: false };
  if (!/^\d{5}$/.test(zip)) {
    return { ok: false, code: 'invalid_zip', field: 'zip', message: `ZIP must be 5 digits; got ${JSON.stringify(zip)}.` };
  }
  const suppliedState = String(sc.state || '').trim().toUpperCase();
  const suppliedFpsEarly = String(sc.countyFps || '').trim();
  const hit = lookupZip(zip);
  if (!hit) {
    // NOTHING TO ENRICH is not a failure. A caller who already supplied the state AND the county
    // FIPS has given us everything the vendor needs, so an unresolvable ZIP must not refuse them —
    // and it would: a PO-box-only ZIP has no ZCTA at all (ZIP 30301 in our own test battery is one),
    // so failing closed unconditionally rejected complete, perfectly valid requests.
    if (suppliedState && suppliedFpsEarly) return { ok: true, location: {}, filled: [], split: false };
    // We genuinely needed the lookup and it has no answer. Fail CLOSED and say how to proceed.
    return { ok: false, code: 'zip_not_found', field: 'zip',
      message: `ZIP ${zip} is not in the Census ZIP-to-county table (vintage ${DATA.vintage}), so its county cannot be resolved. Supply state + countyFps explicitly, or check the ZIP.` };
  }
  const filled = [];
  const location = {};
  if (!suppliedState) { location.state = hit.state; filled.push('state'); }
  else if (suppliedState !== hit.state) {
    return { ok: false, code: 'location_conflict', field: 'state',
      message: `ZIP ${zip} is in ${hit.state}, but state ${suppliedState} was supplied. Fix the conflicting location.` };
  }
  const suppliedFps = String(sc.countyFps || '').trim();
  if (!suppliedFps) { location.countyFps = hit.countyFps; filled.push('countyFps'); }
  else if (suppliedFps !== hit.countyFps) {
    // NOT a conflict when the ZIP genuinely spans counties — the caller's explicit county is the
    // better answer there, and overriding is exactly why `split` is reported. On a single-county
    // ZIP a mismatch is a real contradiction.
    if (!hit.split) {
      return { ok: false, code: 'location_conflict', field: 'countyFps',
        message: `ZIP ${zip} is in county ${hit.countyFps} (${hit.countyName}), but county FIPS ${suppliedFps} was supplied. Fix the conflicting location.` };
    }
  }
  // The county NAME is only filled when we are the one supplying the FIPS, so a caller's explicit
  // county keeps its own name rather than being relabelled with the dominant county's.
  const suppliedName = String(sc.countyName || sc.county || '').trim();
  if (!suppliedName && !suppliedFps) { location.countyName = hit.countyName; filled.push('countyName'); }
  return { ok: true, location, filled, split: hit.split, resolved: hit };
}

module.exports = {
  lookupZip, enrichLocation,
  _internals: { bareCountyName, STATE_BY_FIPS, meta: { vintage: DATA.vintage, source: DATA.source, sourceSha256: DATA.sourceSha256, zipCount: DATA.zipCount, splitZipCount: DATA.splitZipCount } },
};
